/**
 * kanji.js — Axe « Kanji » de l'agent d'apprentissage du japonais
 * --------------------------------------------------------------
 * Les kanji les plus récurrents, regroupés par thèmes. Chaque entrée :
 *   char    : le kanji
 *   on      : lecture on'yomi (キン, sino-japonaise) — "—" si peu courante
 *   kun     : lecture kun'yomi (japonaise) — "—" si peu courante
 *   fr      : sens en français
 *   exemple : { jp, romaji, fr } — un exemple d'utilisation (toujours présent)
 *
 * Ce fichier expose la variable globale KANJI.
 */
const KANJI = [
  {
    categorie: "Nombres",
    icon: "🔢",
    desc: "Les chiffres et unités de base.",
    items: [
      { char: "一", on: "イチ", kun: "ひと(つ)", fr: "un", exemple: { jp: "一人で行きます。", romaji: "Hitori de ikimasu.", fr: "J'y vais seul." } },
      { char: "二", on: "ニ", kun: "ふた(つ)", fr: "deux", exemple: { jp: "二人の友達。", romaji: "Futari no tomodachi.", fr: "Deux amis." } },
      { char: "三", on: "サン", kun: "み(っつ)", fr: "trois", exemple: { jp: "三月に会います。", romaji: "Sangatsu ni aimasu.", fr: "On se voit en mars." } },
      { char: "四", on: "シ", kun: "よ(っつ)", fr: "quatre", exemple: { jp: "四時に来ます。", romaji: "Yoji ni kimasu.", fr: "Je viens à 4 heures." } },
      { char: "五", on: "ゴ", kun: "いつ(つ)", fr: "cinq", exemple: { jp: "五百円です。", romaji: "Gohyaku en desu.", fr: "Ça fait 500 yens." } },
      { char: "六", on: "ロク", kun: "むっ(つ)", fr: "six", exemple: { jp: "六時に起きます。", romaji: "Rokuji ni okimasu.", fr: "Je me lève à 6 heures." } },
      { char: "七", on: "シチ", kun: "なな(つ)", fr: "sept", exemple: { jp: "七月は暑い。", romaji: "Shichigatsu wa atsui.", fr: "Juillet est chaud." } },
      { char: "八", on: "ハチ", kun: "やっ(つ)", fr: "huit", exemple: { jp: "八日に帰ります。", romaji: "Yōka ni kaerimasu.", fr: "Je rentre le 8." } },
      { char: "九", on: "キュウ", kun: "ここの(つ)", fr: "neuf", exemple: { jp: "九月に始まる。", romaji: "Kugatsu ni hajimaru.", fr: "Ça commence en septembre." } },
      { char: "十", on: "ジュウ", kun: "とお", fr: "dix", exemple: { jp: "十日かかります。", romaji: "Tōka kakarimasu.", fr: "Ça prend dix jours." } },
      { char: "百", on: "ヒャク", kun: "—", fr: "cent", exemple: { jp: "百円ください。", romaji: "Hyaku en kudasai.", fr: "100 yens, s'il vous plaît." } },
      { char: "千", on: "セン", kun: "ち", fr: "mille", exemple: { jp: "千円あります。", romaji: "Sen en arimasu.", fr: "J'ai 1000 yens." } },
      { char: "万", on: "マン", kun: "—", fr: "dix mille", exemple: { jp: "一万円です。", romaji: "Ichiman en desu.", fr: "Ça fait 10 000 yens." } },
      { char: "円", on: "エン", kun: "まる(い)", fr: "yen / cercle", exemple: { jp: "五百円玉。", romaji: "Gohyaku-en dama.", fr: "Une pièce de 500 yens." } },
    ],
  },
  {
    categorie: "Jours & temps",
    icon: "📅",
    desc: "Les jours de la semaine et les unités de temps.",
    items: [
      { char: "日", on: "ニチ", kun: "ひ / か", fr: "jour / soleil", exemple: { jp: "日曜日は休みです。", romaji: "Nichiyōbi wa yasumi desu.", fr: "Dimanche est un jour de repos." } },
      { char: "月", on: "ゲツ / ガツ", kun: "つき", fr: "lune / mois", exemple: { jp: "月曜日に働く。", romaji: "Getsuyōbi ni hataraku.", fr: "Je travaille le lundi." } },
      { char: "火", on: "カ", kun: "ひ", fr: "feu", exemple: { jp: "火曜日に会う。", romaji: "Kayōbi ni au.", fr: "On se voit mardi." } },
      { char: "水", on: "スイ", kun: "みず", fr: "eau", exemple: { jp: "水を飲む。", romaji: "Mizu o nomu.", fr: "Boire de l'eau." } },
      { char: "木", on: "モク", kun: "き", fr: "arbre / bois", exemple: { jp: "木曜日は忙しい。", romaji: "Mokuyōbi wa isogashii.", fr: "Jeudi est chargé." } },
      { char: "金", on: "キン", kun: "かね", fr: "or / argent", exemple: { jp: "金曜日が好き。", romaji: "Kin'yōbi ga suki.", fr: "J'aime le vendredi." } },
      { char: "土", on: "ド", kun: "つち", fr: "terre / sol", exemple: { jp: "土曜日に出かける。", romaji: "Doyōbi ni dekakeru.", fr: "Je sors le samedi." } },
      { char: "年", on: "ネン", kun: "とし", fr: "année", exemple: { jp: "今年は忙しい。", romaji: "Kotoshi wa isogashii.", fr: "Cette année est chargée." } },
      { char: "時", on: "ジ", kun: "とき", fr: "heure / temps", exemple: { jp: "時間がありません。", romaji: "Jikan ga arimasen.", fr: "Je n'ai pas le temps." } },
      { char: "分", on: "フン / ブン", kun: "わ(ける)", fr: "minute / partie", exemple: { jp: "五分待って。", romaji: "Gofun matte.", fr: "Attends cinq minutes." } },
      { char: "半", on: "ハン", kun: "なか(ば)", fr: "demi / moitié", exemple: { jp: "一時半に会う。", romaji: "Ichiji-han ni au.", fr: "On se voit à 1h30." } },
      { char: "今", on: "コン", kun: "いま", fr: "maintenant", exemple: { jp: "今、何時ですか。", romaji: "Ima, nanji desu ka.", fr: "Quelle heure est-il ?" } },
      { char: "週", on: "シュウ", kun: "—", fr: "semaine", exemple: { jp: "来週会いましょう。", romaji: "Raishū aimashō.", fr: "Voyons-nous la semaine prochaine." } },
      { char: "毎", on: "マイ", kun: "—", fr: "chaque", exemple: { jp: "毎日勉強する。", romaji: "Mainichi benkyō suru.", fr: "J'étudie tous les jours." } },
    ],
  },
  {
    categorie: "La nature",
    icon: "🌿",
    desc: "Éléments naturels et paysages.",
    items: [
      { char: "山", on: "サン", kun: "やま", fr: "montagne", exemple: { jp: "富士山を見る。", romaji: "Fujisan o miru.", fr: "Voir le mont Fuji." } },
      { char: "川", on: "セン", kun: "かわ", fr: "rivière", exemple: { jp: "川を渡る。", romaji: "Kawa o wataru.", fr: "Traverser la rivière." } },
      { char: "田", on: "デン", kun: "た", fr: "rizière", exemple: { jp: "田んぼで働く。", romaji: "Tanbo de hataraku.", fr: "Travailler dans la rizière." } },
      { char: "花", on: "カ", kun: "はな", fr: "fleur", exemple: { jp: "花見に行く。", romaji: "Hanami ni iku.", fr: "Aller admirer les fleurs." } },
      { char: "草", on: "ソウ", kun: "くさ", fr: "herbe", exemple: { jp: "草が生える。", romaji: "Kusa ga haeru.", fr: "L'herbe pousse." } },
      { char: "空", on: "クウ", kun: "そら", fr: "ciel / vide", exemple: { jp: "空が青い。", romaji: "Sora ga aoi.", fr: "Le ciel est bleu." } },
      { char: "海", on: "カイ", kun: "うみ", fr: "mer", exemple: { jp: "海で泳ぐ。", romaji: "Umi de oyogu.", fr: "Nager dans la mer." } },
      { char: "天", on: "テン", kun: "あま", fr: "ciel / cieux", exemple: { jp: "天気がいい。", romaji: "Tenki ga ii.", fr: "Il fait beau." } },
      { char: "気", on: "キ / ケ", kun: "—", fr: "air / esprit", exemple: { jp: "元気ですか。", romaji: "Genki desu ka.", fr: "Comment allez-vous ?" } },
      { char: "雨", on: "ウ", kun: "あめ", fr: "pluie", exemple: { jp: "雨が降る。", romaji: "Ame ga furu.", fr: "Il pleut." } },
      { char: "雪", on: "セツ", kun: "ゆき", fr: "neige", exemple: { jp: "雪が降る。", romaji: "Yuki ga furu.", fr: "Il neige." } },
      { char: "風", on: "フウ", kun: "かぜ", fr: "vent", exemple: { jp: "風が強い。", romaji: "Kaze ga tsuyoi.", fr: "Le vent est fort." } },
      { char: "林", on: "リン", kun: "はやし", fr: "bois / bosquet", exemple: { jp: "林の中を歩く。", romaji: "Hayashi no naka o aruku.", fr: "Marcher dans le bois." } },
      { char: "森", on: "シン", kun: "もり", fr: "forêt", exemple: { jp: "森は静かだ。", romaji: "Mori wa shizuka da.", fr: "La forêt est calme." } },
    ],
  },
  {
    categorie: "Personnes & famille",
    icon: "👪",
    desc: "Les gens, la famille et l'identité.",
    items: [
      { char: "人", on: "ジン / ニン", kun: "ひと", fr: "personne", exemple: { jp: "日本人です。", romaji: "Nihonjin desu.", fr: "Je suis japonais(e)." } },
      { char: "男", on: "ダン", kun: "おとこ", fr: "homme", exemple: { jp: "男の子。", romaji: "Otoko no ko.", fr: "Un garçon." } },
      { char: "女", on: "ジョ", kun: "おんな", fr: "femme", exemple: { jp: "女の人。", romaji: "Onna no hito.", fr: "Une femme." } },
      { char: "子", on: "シ", kun: "こ", fr: "enfant", exemple: { jp: "子供が遊ぶ。", romaji: "Kodomo ga asobu.", fr: "Les enfants jouent." } },
      { char: "父", on: "フ", kun: "ちち", fr: "père", exemple: { jp: "父は医者だ。", romaji: "Chichi wa isha da.", fr: "Mon père est médecin." } },
      { char: "母", on: "ボ", kun: "はは", fr: "mère", exemple: { jp: "母に電話する。", romaji: "Haha ni denwa suru.", fr: "J'appelle ma mère." } },
      { char: "兄", on: "ケイ", kun: "あに", fr: "grand frère", exemple: { jp: "兄がいます。", romaji: "Ani ga imasu.", fr: "J'ai un grand frère." } },
      { char: "姉", on: "シ", kun: "あね", fr: "grande sœur", exemple: { jp: "姉は先生だ。", romaji: "Ane wa sensei da.", fr: "Ma sœur est professeure." } },
      { char: "友", on: "ユウ", kun: "とも", fr: "ami", exemple: { jp: "友達と遊ぶ。", romaji: "Tomodachi to asobu.", fr: "Je joue avec des amis." } },
      { char: "名", on: "メイ", kun: "な", fr: "nom", exemple: { jp: "名前は何ですか。", romaji: "Namae wa nan desu ka.", fr: "Quel est votre nom ?" } },
      { char: "先", on: "セン", kun: "さき", fr: "avant / devant", exemple: { jp: "先生に聞く。", romaji: "Sensei ni kiku.", fr: "Demander au professeur." } },
      { char: "生", on: "セイ", kun: "い(きる)", fr: "vie / naître", exemple: { jp: "学生です。", romaji: "Gakusei desu.", fr: "Je suis étudiant(e)." } },
    ],
  },
  {
    categorie: "Le corps",
    icon: "🧍",
    desc: "Les parties du corps et notions liées.",
    items: [
      { char: "目", on: "モク", kun: "め", fr: "œil", exemple: { jp: "目が痛い。", romaji: "Me ga itai.", fr: "J'ai mal aux yeux." } },
      { char: "耳", on: "ジ", kun: "みみ", fr: "oreille", exemple: { jp: "耳が良い。", romaji: "Mimi ga ii.", fr: "Avoir l'oreille fine." } },
      { char: "口", on: "コウ", kun: "くち", fr: "bouche", exemple: { jp: "口を開ける。", romaji: "Kuchi o akeru.", fr: "Ouvrir la bouche." } },
      { char: "手", on: "シュ", kun: "て", fr: "main", exemple: { jp: "手を洗う。", romaji: "Te o arau.", fr: "Se laver les mains." } },
      { char: "足", on: "ソク", kun: "あし", fr: "pied / jambe", exemple: { jp: "足が痛い。", romaji: "Ashi ga itai.", fr: "J'ai mal au pied." } },
      { char: "体", on: "タイ", kun: "からだ", fr: "corps", exemple: { jp: "体にいい。", romaji: "Karada ni ii.", fr: "C'est bon pour le corps." } },
      { char: "心", on: "シン", kun: "こころ", fr: "cœur / esprit", exemple: { jp: "心が広い。", romaji: "Kokoro ga hiroi.", fr: "Avoir grand cœur." } },
      { char: "力", on: "リョク", kun: "ちから", fr: "force", exemple: { jp: "力が強い。", romaji: "Chikara ga tsuyoi.", fr: "Être fort." } },
    ],
  },
  {
    categorie: "Position & directions",
    icon: "🧭",
    desc: "Se repérer dans l'espace.",
    items: [
      { char: "上", on: "ジョウ", kun: "うえ", fr: "haut / dessus", exemple: { jp: "机の上に本がある。", romaji: "Tsukue no ue ni hon ga aru.", fr: "Il y a un livre sur le bureau." } },
      { char: "下", on: "カ", kun: "した", fr: "bas / dessous", exemple: { jp: "机の下に猫がいる。", romaji: "Tsukue no shita ni neko ga iru.", fr: "Il y a un chat sous le bureau." } },
      { char: "中", on: "チュウ", kun: "なか", fr: "milieu / dans", exemple: { jp: "家の中にいる。", romaji: "Ie no naka ni iru.", fr: "Être dans la maison." } },
      { char: "外", on: "ガイ", kun: "そと", fr: "dehors / extérieur", exemple: { jp: "外で遊ぶ。", romaji: "Soto de asobu.", fr: "Jouer dehors." } },
      { char: "右", on: "ウ", kun: "みぎ", fr: "droite", exemple: { jp: "右に曲がる。", romaji: "Migi ni magaru.", fr: "Tourner à droite." } },
      { char: "左", on: "サ", kun: "ひだり", fr: "gauche", exemple: { jp: "左を見る。", romaji: "Hidari o miru.", fr: "Regarder à gauche." } },
      { char: "前", on: "ゼン", kun: "まえ", fr: "devant / avant", exemple: { jp: "駅の前で待つ。", romaji: "Eki no mae de matsu.", fr: "Attendre devant la gare." } },
      { char: "後", on: "ゴ", kun: "うし(ろ)", fr: "après / derrière", exemple: { jp: "午後に会う。", romaji: "Gogo ni au.", fr: "Se voir l'après-midi." } },
      { char: "内", on: "ナイ", kun: "うち", fr: "intérieur", exemple: { jp: "店内は静かだ。", romaji: "Tennai wa shizuka da.", fr: "L'intérieur du magasin est calme." } },
    ],
  },
  {
    categorie: "Adjectifs & couleurs",
    icon: "✨",
    desc: "Les qualités et les couleurs de base.",
    items: [
      { char: "大", on: "ダイ", kun: "おお(きい)", fr: "grand", exemple: { jp: "大きい犬。", romaji: "Ōkii inu.", fr: "Un grand chien." } },
      { char: "小", on: "ショウ", kun: "ちい(さい)", fr: "petit", exemple: { jp: "小さい猫。", romaji: "Chiisai neko.", fr: "Un petit chat." } },
      { char: "高", on: "コウ", kun: "たか(い)", fr: "haut / cher", exemple: { jp: "高い山。", romaji: "Takai yama.", fr: "Une haute montagne." } },
      { char: "安", on: "アン", kun: "やす(い)", fr: "bon marché / paisible", exemple: { jp: "安い店。", romaji: "Yasui mise.", fr: "Un magasin bon marché." } },
      { char: "新", on: "シン", kun: "あたら(しい)", fr: "nouveau", exemple: { jp: "新しい車。", romaji: "Atarashii kuruma.", fr: "Une voiture neuve." } },
      { char: "古", on: "コ", kun: "ふる(い)", fr: "vieux / ancien", exemple: { jp: "古い本。", romaji: "Furui hon.", fr: "Un vieux livre." } },
      { char: "長", on: "チョウ", kun: "なが(い)", fr: "long / chef", exemple: { jp: "長い道。", romaji: "Nagai michi.", fr: "Une longue route." } },
      { char: "多", on: "タ", kun: "おお(い)", fr: "nombreux", exemple: { jp: "人が多い。", romaji: "Hito ga ōi.", fr: "Il y a beaucoup de monde." } },
      { char: "少", on: "ショウ", kun: "すく(ない)", fr: "peu", exemple: { jp: "少し待って。", romaji: "Sukoshi matte.", fr: "Attends un peu." } },
      { char: "白", on: "ハク", kun: "しろ", fr: "blanc", exemple: { jp: "白い雪。", romaji: "Shiroi yuki.", fr: "De la neige blanche." } },
      { char: "黒", on: "コク", kun: "くろ", fr: "noir", exemple: { jp: "黒い猫。", romaji: "Kuroi neko.", fr: "Un chat noir." } },
      { char: "赤", on: "セキ", kun: "あか", fr: "rouge", exemple: { jp: "赤い花。", romaji: "Akai hana.", fr: "Une fleur rouge." } },
      { char: "青", on: "セイ", kun: "あお", fr: "bleu", exemple: { jp: "青い空。", romaji: "Aoi sora.", fr: "Un ciel bleu." } },
      { char: "早", on: "ソウ", kun: "はや(い)", fr: "tôt / rapide", exemple: { jp: "早く起きる。", romaji: "Hayaku okiru.", fr: "Se lever tôt." } },
    ],
  },
  {
    categorie: "Verbes essentiels",
    icon: "🔀",
    desc: "Les kanji des actions les plus fréquentes.",
    items: [
      { char: "行", on: "コウ", kun: "い(く)", fr: "aller", exemple: { jp: "学校に行く。", romaji: "Gakkō ni iku.", fr: "Aller à l'école." } },
      { char: "来", on: "ライ", kun: "く(る)", fr: "venir", exemple: { jp: "友達が来る。", romaji: "Tomodachi ga kuru.", fr: "Un ami vient." } },
      { char: "見", on: "ケン", kun: "み(る)", fr: "voir / regarder", exemple: { jp: "映画を見る。", romaji: "Eiga o miru.", fr: "Regarder un film." } },
      { char: "聞", on: "ブン", kun: "き(く)", fr: "écouter / demander", exemple: { jp: "音楽を聞く。", romaji: "Ongaku o kiku.", fr: "Écouter de la musique." } },
      { char: "食", on: "ショク", kun: "た(べる)", fr: "manger", exemple: { jp: "ご飯を食べる。", romaji: "Gohan o taberu.", fr: "Manger du riz." } },
      { char: "飲", on: "イン", kun: "の(む)", fr: "boire", exemple: { jp: "お茶を飲む。", romaji: "Ocha o nomu.", fr: "Boire du thé." } },
      { char: "言", on: "ゲン", kun: "い(う)", fr: "dire", exemple: { jp: "名前を言う。", romaji: "Namae o iu.", fr: "Dire son nom." } },
      { char: "話", on: "ワ", kun: "はな(す)", fr: "parler / histoire", exemple: { jp: "日本語を話す。", romaji: "Nihongo o hanasu.", fr: "Parler japonais." } },
      { char: "読", on: "ドク", kun: "よ(む)", fr: "lire", exemple: { jp: "本を読む。", romaji: "Hon o yomu.", fr: "Lire un livre." } },
      { char: "書", on: "ショ", kun: "か(く)", fr: "écrire", exemple: { jp: "手紙を書く。", romaji: "Tegami o kaku.", fr: "Écrire une lettre." } },
      { char: "買", on: "バイ", kun: "か(う)", fr: "acheter", exemple: { jp: "パンを買う。", romaji: "Pan o kau.", fr: "Acheter du pain." } },
      { char: "出", on: "シュツ", kun: "で(る)", fr: "sortir", exemple: { jp: "家を出る。", romaji: "Ie o deru.", fr: "Sortir de la maison." } },
      { char: "入", on: "ニュウ", kun: "はい(る)", fr: "entrer", exemple: { jp: "部屋に入る。", romaji: "Heya ni hairu.", fr: "Entrer dans la pièce." } },
      { char: "立", on: "リツ", kun: "た(つ)", fr: "se tenir debout", exemple: { jp: "立ってください。", romaji: "Tatte kudasai.", fr: "Levez-vous, s'il vous plaît." } },
    ],
  },
  {
    categorie: "Lieux & société",
    icon: "🏙️",
    desc: "La ville, l'école, les transports et le travail.",
    items: [
      { char: "国", on: "コク", kun: "くに", fr: "pays", exemple: { jp: "外国に行く。", romaji: "Gaikoku ni iku.", fr: "Aller à l'étranger." } },
      { char: "学", on: "ガク", kun: "まな(ぶ)", fr: "étude / apprendre", exemple: { jp: "学校で学ぶ。", romaji: "Gakkō de manabu.", fr: "Apprendre à l'école." } },
      { char: "校", on: "コウ", kun: "—", fr: "école (établissement)", exemple: { jp: "高校に通う。", romaji: "Kōkō ni kayou.", fr: "Aller au lycée." } },
      { char: "本", on: "ホン", kun: "もと", fr: "livre / origine", exemple: { jp: "日本の本。", romaji: "Nihon no hon.", fr: "Un livre du Japon." } },
      { char: "語", on: "ゴ", kun: "かた(る)", fr: "langue / mot", exemple: { jp: "日本語を勉強する。", romaji: "Nihongo o benkyō suru.", fr: "Étudier le japonais." } },
      { char: "店", on: "テン", kun: "みせ", fr: "magasin", exemple: { jp: "店に行く。", romaji: "Mise ni iku.", fr: "Aller au magasin." } },
      { char: "駅", on: "エキ", kun: "—", fr: "gare / station", exemple: { jp: "駅で会う。", romaji: "Eki de au.", fr: "Se retrouver à la gare." } },
      { char: "車", on: "シャ", kun: "くるま", fr: "voiture / véhicule", exemple: { jp: "電車に乗る。", romaji: "Densha ni noru.", fr: "Prendre le train." } },
      { char: "道", on: "ドウ", kun: "みち", fr: "route / chemin", exemple: { jp: "道を歩く。", romaji: "Michi o aruku.", fr: "Marcher sur la route." } },
      { char: "町", on: "チョウ", kun: "まち", fr: "ville / quartier", exemple: { jp: "町を歩く。", romaji: "Machi o aruku.", fr: "Se promener en ville." } },
      { char: "市", on: "シ", kun: "いち", fr: "ville / marché", exemple: { jp: "市役所へ行く。", romaji: "Shiyakusho e iku.", fr: "Aller à la mairie." } },
      { char: "社", on: "シャ", kun: "やしろ", fr: "société / sanctuaire", exemple: { jp: "会社で働く。", romaji: "Kaisha de hataraku.", fr: "Travailler dans une entreprise." } },
      { char: "会", on: "カイ", kun: "あ(う)", fr: "réunion / rencontrer", exemple: { jp: "会議があります。", romaji: "Kaigi ga arimasu.", fr: "Il y a une réunion." } },
      { char: "員", on: "イン", kun: "—", fr: "membre / employé", exemple: { jp: "会社員です。", romaji: "Kaishain desu.", fr: "Je suis employé(e)." } },
      { char: "電", on: "デン", kun: "—", fr: "électricité", exemple: { jp: "電話をする。", romaji: "Denwa o suru.", fr: "Téléphoner." } },
      { char: "屋", on: "オク", kun: "や", fr: "boutique / toit", exemple: { jp: "本屋に行く。", romaji: "Hon'ya ni iku.", fr: "Aller à la librairie." } },
    ],
  },
  {
    categorie: "Autres kanji fréquents",
    icon: "📌",
    desc: "Des kanji très courants du quotidien.",
    items: [
      { char: "休", on: "キュウ", kun: "やす(む)", fr: "repos / se reposer", exemple: { jp: "日曜日は休む。", romaji: "Nichiyōbi wa yasumu.", fr: "Je me repose le dimanche." } },
      { char: "物", on: "ブツ", kun: "もの", fr: "chose / objet", exemple: { jp: "食べ物が好き。", romaji: "Tabemono ga suki.", fr: "J'aime la nourriture." } },
      { char: "事", on: "ジ", kun: "こと", fr: "chose / affaire", exemple: { jp: "仕事をする。", romaji: "Shigoto o suru.", fr: "Travailler." } },
      { char: "自", on: "ジ", kun: "みずか(ら)", fr: "soi-même", exemple: { jp: "自分でする。", romaji: "Jibun de suru.", fr: "Le faire soi-même." } },
      { char: "間", on: "カン", kun: "あいだ", fr: "intervalle / entre", exemple: { jp: "人間はみな違う。", romaji: "Ningen wa mina chigau.", fr: "Les humains sont tous différents." } },
      { char: "東", on: "トウ", kun: "ひがし", fr: "est", exemple: { jp: "東京に住む。", romaji: "Tōkyō ni sumu.", fr: "Habiter à Tokyo." } },
      { char: "西", on: "セイ", kun: "にし", fr: "ouest", exemple: { jp: "西へ行く。", romaji: "Nishi e iku.", fr: "Aller vers l'ouest." } },
      { char: "南", on: "ナン", kun: "みなみ", fr: "sud", exemple: { jp: "南は暖かい。", romaji: "Minami wa atatakai.", fr: "Le sud est chaud." } },
      { char: "北", on: "ホク", kun: "きた", fr: "nord", exemple: { jp: "北は寒い。", romaji: "Kita wa samui.", fr: "Le nord est froid." } },
      { char: "京", on: "キョウ", kun: "—", fr: "capitale", exemple: { jp: "京都は美しい。", romaji: "Kyōto wa utsukushii.", fr: "Kyoto est magnifique." } },
      { char: "番", on: "バン", kun: "—", fr: "numéro / tour", exemple: { jp: "一番好きです。", romaji: "Ichiban suki desu.", fr: "C'est ce que je préfère." } },
      { char: "楽", on: "ガク / ラク", kun: "たの(しい)", fr: "musique / plaisir", exemple: { jp: "音楽を楽しむ。", romaji: "Ongaku o tanoshimu.", fr: "Apprécier la musique." } },
    ],
  },
];

/* Exposé global */
if (typeof window !== "undefined") window.KANJI = KANJI;
