/**
 * vocab.js — Vocabulaire de l'agent d'apprentissage du japonais
 * -------------------------------------------------------------
 * 21 thèmes d'apprentissage, au moins 50 mots par thème.
 * Chaque entrée : jp (kanji/kana), kana (lecture), romaji, fr, img (emoji).
 * Ce fichier expose la constante globale VOCABULAIRE utilisée par data.js.
 */
const VOCABULAIRE = [
  {
    theme: "Salutations & politesse",
    icon: "👋",
    mots: [
      { jp: "こんにちは", kana: "こんにちは", romaji: "konnichiwa", fr: "bonjour", img: "☀️" },
      { jp: "おはようございます", kana: "おはようございます", romaji: "ohayō gozaimasu", fr: "bonjour (matin, poli)", img: "🌅" },
      { jp: "おはよう", kana: "おはよう", romaji: "ohayō", fr: "salut (le matin)", img: "🌄" },
      { jp: "こんばんは", kana: "こんばんは", romaji: "konbanwa", fr: "bonsoir", img: "🌆" },
      { jp: "おやすみなさい", kana: "おやすみなさい", romaji: "oyasuminasai", fr: "bonne nuit", img: "😴" },
      { jp: "さようなら", kana: "さようなら", romaji: "sayōnara", fr: "au revoir", img: "👋" },
      { jp: "じゃあね", kana: "じゃあね", romaji: "jā ne", fr: "à plus (informel)", img: "🙋" },
      { jp: "またね", kana: "またね", romaji: "mata ne", fr: "à bientôt", img: "✋" },
      { jp: "また明日", kana: "またあした", romaji: "mata ashita", fr: "à demain", img: "📅" },
      { jp: "ありがとう", kana: "ありがとう", romaji: "arigatō", fr: "merci", img: "🙏" },
      { jp: "ありがとうございます", kana: "ありがとうございます", romaji: "arigatō gozaimasu", fr: "merci beaucoup (poli)", img: "🙇" },
      { jp: "どういたしまして", kana: "どういたしまして", romaji: "dō itashimashite", fr: "de rien", img: "😊" },
      { jp: "すみません", kana: "すみません", romaji: "sumimasen", fr: "excusez-moi / pardon", img: "🙇" },
      { jp: "ごめんなさい", kana: "ごめんなさい", romaji: "gomen nasai", fr: "désolé(e)", img: "😔" },
      { jp: "お願いします", kana: "おねがいします", romaji: "onegai shimasu", fr: "s'il vous plaît", img: "🤲" },
      { jp: "はい", kana: "はい", romaji: "hai", fr: "oui", img: "✅" },
      { jp: "いいえ", kana: "いいえ", romaji: "iie", fr: "non", img: "❌" },
      { jp: "はじめまして", kana: "はじめまして", romaji: "hajimemashite", fr: "enchanté(e)", img: "🤝" },
      { jp: "よろしくお願いします", kana: "よろしくおねがいします", romaji: "yoroshiku onegai shimasu", fr: "ravi de vous rencontrer", img: "🤝" },
      { jp: "お元気ですか", kana: "おげんきですか", romaji: "ogenki desu ka", fr: "comment allez-vous ?", img: "😊" },
      { jp: "元気です", kana: "げんきです", romaji: "genki desu", fr: "je vais bien", img: "💪" },
      { jp: "おかげさまで", kana: "おかげさまで", romaji: "okagesama de", fr: "grâce à vous", img: "🙏" },
      { jp: "久しぶり", kana: "ひさしぶり", romaji: "hisashiburi", fr: "ça faisait longtemps", img: "🕰️" },
      { jp: "お久しぶりです", kana: "おひさしぶりです", romaji: "ohisashiburi desu", fr: "ça fait longtemps (poli)", img: "⌛" },
      { jp: "いってきます", kana: "いってきます", romaji: "ittekimasu", fr: "j'y vais (je pars)", img: "🚪" },
      { jp: "いってらっしゃい", kana: "いってらっしゃい", romaji: "itterasshai", fr: "à tout à l'heure (au partant)", img: "👋" },
      { jp: "ただいま", kana: "ただいま", romaji: "tadaima", fr: "je suis rentré(e)", img: "🏠" },
      { jp: "おかえりなさい", kana: "おかえりなさい", romaji: "okaerinasai", fr: "bon retour", img: "🏡" },
      { jp: "いただきます", kana: "いただきます", romaji: "itadakimasu", fr: "bon appétit (avant de manger)", img: "🍚" },
      { jp: "ごちそうさまでした", kana: "ごちそうさまでした", romaji: "gochisōsama deshita", fr: "merci pour le repas", img: "🍽️" },
      { jp: "お疲れ様です", kana: "おつかれさまです", romaji: "otsukaresama desu", fr: "bon courage / merci du travail", img: "💼" },
      { jp: "失礼します", kana: "しつれいします", romaji: "shitsurei shimasu", fr: "excusez-moi (je me retire)", img: "🚪" },
      { jp: "失礼しました", kana: "しつれいしました", romaji: "shitsurei shimashita", fr: "pardon (pour la gêne)", img: "🙇" },
      { jp: "どうぞ", kana: "どうぞ", romaji: "dōzo", fr: "je vous en prie", img: "🤲" },
      { jp: "どうも", kana: "どうも", romaji: "dōmo", fr: "merci / bonjour (informel)", img: "🙂" },
      { jp: "おめでとうございます", kana: "おめでとうございます", romaji: "omedetō gozaimasu", fr: "félicitations (poli)", img: "🎉" },
      { jp: "お誕生日おめでとう", kana: "おたんじょうびおめでとう", romaji: "otanjōbi omedetō", fr: "joyeux anniversaire", img: "🎂" },
      { jp: "いらっしゃいませ", kana: "いらっしゃいませ", romaji: "irasshaimase", fr: "bienvenue (dans un commerce)", img: "🏬" },
      { jp: "かしこまりました", kana: "かしこまりました", romaji: "kashikomarimashita", fr: "bien, entendu (très poli)", img: "🙇" },
      { jp: "もしもし", kana: "もしもし", romaji: "moshi moshi", fr: "allô (au téléphone)", img: "📞" },
      { jp: "お名前は", kana: "おなまえは", romaji: "onamae wa", fr: "quel est votre nom ?", img: "🪪" },
      { jp: "私の名前は", kana: "わたしのなまえは", romaji: "watashi no namae wa", fr: "je m'appelle…", img: "🙋" },
      { jp: "お先に失礼します", kana: "おさきにしつれいします", romaji: "osaki ni shitsurei shimasu", fr: "je pars avant vous", img: "🚶" },
      { jp: "気にしないで", kana: "きにしないで", romaji: "ki ni shinaide", fr: "ne t'en fais pas", img: "🙂" },
      { jp: "大丈夫です", kana: "だいじょうぶです", romaji: "daijōbu desu", fr: "ça va / pas de souci", img: "👌" },
      { jp: "とんでもないです", kana: "とんでもないです", romaji: "tondemonai desu", fr: "pas du tout (je vous en prie)", img: "🙅" },
      { jp: "お世話になりました", kana: "おせわになりました", romaji: "osewa ni narimashita", fr: "merci de votre aide", img: "🙏" },
      { jp: "よろしく", kana: "よろしく", romaji: "yoroshiku", fr: "à bientôt (informel)", img: "✌️" },
      { jp: "ようこそ", kana: "ようこそ", romaji: "yōkoso", fr: "bienvenue", img: "🎊" },
      { jp: "ご無沙汰しております", kana: "ごぶさたしております", romaji: "gobusata shite orimasu", fr: "désolé du long silence (poli)", img: "🕰️" },
    ],
  },
  {
    theme: "Nombres",
    icon: "🔢",
    mots: [
      { jp: "ゼロ", kana: "ゼロ", romaji: "zero", fr: "zéro (0)", img: "0️⃣" },
      { jp: "一", kana: "いち", romaji: "ichi", fr: "un (1)", img: "1️⃣" },
      { jp: "二", kana: "に", romaji: "ni", fr: "deux (2)", img: "2️⃣" },
      { jp: "三", kana: "さん", romaji: "san", fr: "trois (3)", img: "3️⃣" },
      { jp: "四", kana: "よん", romaji: "yon / shi", fr: "quatre (4)", img: "4️⃣" },
      { jp: "五", kana: "ご", romaji: "go", fr: "cinq (5)", img: "5️⃣" },
      { jp: "六", kana: "ろく", romaji: "roku", fr: "six (6)", img: "6️⃣" },
      { jp: "七", kana: "なな", romaji: "nana / shichi", fr: "sept (7)", img: "7️⃣" },
      { jp: "八", kana: "はち", romaji: "hachi", fr: "huit (8)", img: "8️⃣" },
      { jp: "九", kana: "きゅう", romaji: "kyū / ku", fr: "neuf (9)", img: "9️⃣" },
      { jp: "十", kana: "じゅう", romaji: "jū", fr: "dix (10)", img: "🔟" },
      { jp: "十一", kana: "じゅういち", romaji: "jūichi", fr: "onze (11)", img: "🔢" },
      { jp: "十二", kana: "じゅうに", romaji: "jūni", fr: "douze (12)", img: "🔢" },
      { jp: "十三", kana: "じゅうさん", romaji: "jūsan", fr: "treize (13)", img: "🔢" },
      { jp: "十四", kana: "じゅうよん", romaji: "jūyon", fr: "quatorze (14)", img: "🔢" },
      { jp: "十五", kana: "じゅうご", romaji: "jūgo", fr: "quinze (15)", img: "🔢" },
      { jp: "十六", kana: "じゅうろく", romaji: "jūroku", fr: "seize (16)", img: "🔢" },
      { jp: "十七", kana: "じゅうなな", romaji: "jūnana", fr: "dix-sept (17)", img: "🔢" },
      { jp: "十八", kana: "じゅうはち", romaji: "jūhachi", fr: "dix-huit (18)", img: "🔢" },
      { jp: "十九", kana: "じゅうきゅう", romaji: "jūkyū", fr: "dix-neuf (19)", img: "🔢" },
      { jp: "二十", kana: "にじゅう", romaji: "nijū", fr: "vingt (20)", img: "🔢" },
      { jp: "三十", kana: "さんじゅう", romaji: "sanjū", fr: "trente (30)", img: "🔢" },
      { jp: "四十", kana: "よんじゅう", romaji: "yonjū", fr: "quarante (40)", img: "🔢" },
      { jp: "五十", kana: "ごじゅう", romaji: "gojū", fr: "cinquante (50)", img: "🔢" },
      { jp: "六十", kana: "ろくじゅう", romaji: "rokujū", fr: "soixante (60)", img: "🔢" },
      { jp: "七十", kana: "ななじゅう", romaji: "nanajū", fr: "soixante-dix (70)", img: "🔢" },
      { jp: "八十", kana: "はちじゅう", romaji: "hachijū", fr: "quatre-vingts (80)", img: "🔢" },
      { jp: "九十", kana: "きゅうじゅう", romaji: "kyūjū", fr: "quatre-vingt-dix (90)", img: "🔢" },
      { jp: "百", kana: "ひゃく", romaji: "hyaku", fr: "cent (100)", img: "💯" },
      { jp: "二百", kana: "にひゃく", romaji: "nihyaku", fr: "deux cents (200)", img: "🔢" },
      { jp: "三百", kana: "さんびゃく", romaji: "sanbyaku", fr: "trois cents (300)", img: "🔢" },
      { jp: "五百", kana: "ごひゃく", romaji: "gohyaku", fr: "cinq cents (500)", img: "🔢" },
      { jp: "六百", kana: "ろっぴゃく", romaji: "roppyaku", fr: "six cents (600)", img: "🔢" },
      { jp: "八百", kana: "はっぴゃく", romaji: "happyaku", fr: "huit cents (800)", img: "🔢" },
      { jp: "千", kana: "せん", romaji: "sen", fr: "mille (1000)", img: "🔢" },
      { jp: "二千", kana: "にせん", romaji: "nisen", fr: "deux mille (2000)", img: "🔢" },
      { jp: "三千", kana: "さんぜん", romaji: "sanzen", fr: "trois mille (3000)", img: "🔢" },
      { jp: "一万", kana: "いちまん", romaji: "ichiman", fr: "dix mille (10 000)", img: "🔢" },
      { jp: "十万", kana: "じゅうまん", romaji: "jūman", fr: "cent mille (100 000)", img: "🔢" },
      { jp: "百万", kana: "ひゃくまん", romaji: "hyakuman", fr: "un million", img: "🔢" },
      { jp: "半分", kana: "はんぶん", romaji: "hanbun", fr: "la moitié", img: "➗" },
      { jp: "番号", kana: "ばんごう", romaji: "bangō", fr: "numéro", img: "🔢" },
      { jp: "一番", kana: "いちばん", romaji: "ichiban", fr: "le premier / numéro un", img: "🥇" },
      { jp: "二番目", kana: "にばんめ", romaji: "nibanme", fr: "le deuxième", img: "🥈" },
      { jp: "一つ", kana: "ひとつ", romaji: "hitotsu", fr: "un (objet)", img: "☝️" },
      { jp: "二つ", kana: "ふたつ", romaji: "futatsu", fr: "deux (objets)", img: "✌️" },
      { jp: "三つ", kana: "みっつ", romaji: "mittsu", fr: "trois (objets)", img: "🤟" },
      { jp: "いくつ", kana: "いくつ", romaji: "ikutsu", fr: "combien (objets)", img: "❓" },
      { jp: "何番", kana: "なんばん", romaji: "nanban", fr: "quel numéro", img: "❔" },
      { jp: "数字", kana: "すうじ", romaji: "sūji", fr: "chiffre", img: "🔢" },
    ],
  },
  {
    theme: "Temps & jours",
    icon: "📅",
    mots: [
      { jp: "今", kana: "いま", romaji: "ima", fr: "maintenant", img: "⏰" },
      { jp: "今日", kana: "きょう", romaji: "kyō", fr: "aujourd'hui", img: "📆" },
      { jp: "明日", kana: "あした", romaji: "ashita", fr: "demain", img: "⏩" },
      { jp: "昨日", kana: "きのう", romaji: "kinō", fr: "hier", img: "⏪" },
      { jp: "明後日", kana: "あさって", romaji: "asatte", fr: "après-demain", img: "⏭️" },
      { jp: "一昨日", kana: "おととい", romaji: "ototoi", fr: "avant-hier", img: "⏮️" },
      { jp: "朝", kana: "あさ", romaji: "asa", fr: "matin", img: "🌅" },
      { jp: "昼", kana: "ひる", romaji: "hiru", fr: "midi / journée", img: "🌞" },
      { jp: "夕方", kana: "ゆうがた", romaji: "yūgata", fr: "fin d'après-midi", img: "🌇" },
      { jp: "夜", kana: "よる", romaji: "yoru", fr: "nuit / soir", img: "🌙" },
      { jp: "午前", kana: "ごぜん", romaji: "gozen", fr: "matin (a.m.)", img: "🕗" },
      { jp: "午後", kana: "ごご", romaji: "gogo", fr: "après-midi (p.m.)", img: "🕒" },
      { jp: "毎日", kana: "まいにち", romaji: "mainichi", fr: "tous les jours", img: "🔁" },
      { jp: "毎朝", kana: "まいあさ", romaji: "maiasa", fr: "chaque matin", img: "🌅" },
      { jp: "毎晩", kana: "まいばん", romaji: "maiban", fr: "chaque soir", img: "🌃" },
      { jp: "週", kana: "しゅう", romaji: "shū", fr: "semaine", img: "🗓️" },
      { jp: "今週", kana: "こんしゅう", romaji: "konshū", fr: "cette semaine", img: "📅" },
      { jp: "来週", kana: "らいしゅう", romaji: "raishū", fr: "la semaine prochaine", img: "⏭️" },
      { jp: "先週", kana: "せんしゅう", romaji: "senshū", fr: "la semaine dernière", img: "⏮️" },
      { jp: "週末", kana: "しゅうまつ", romaji: "shūmatsu", fr: "week-end", img: "🎉" },
      { jp: "月曜日", kana: "げつようび", romaji: "getsuyōbi", fr: "lundi", img: "📅" },
      { jp: "火曜日", kana: "かようび", romaji: "kayōbi", fr: "mardi", img: "📅" },
      { jp: "水曜日", kana: "すいようび", romaji: "suiyōbi", fr: "mercredi", img: "📅" },
      { jp: "木曜日", kana: "もくようび", romaji: "mokuyōbi", fr: "jeudi", img: "📅" },
      { jp: "金曜日", kana: "きんようび", romaji: "kin'yōbi", fr: "vendredi", img: "📅" },
      { jp: "土曜日", kana: "どようび", romaji: "doyōbi", fr: "samedi", img: "📅" },
      { jp: "日曜日", kana: "にちようび", romaji: "nichiyōbi", fr: "dimanche", img: "📅" },
      { jp: "月", kana: "つき", romaji: "tsuki", fr: "mois / lune", img: "🌙" },
      { jp: "今月", kana: "こんげつ", romaji: "kongetsu", fr: "ce mois-ci", img: "📅" },
      { jp: "来月", kana: "らいげつ", romaji: "raigetsu", fr: "le mois prochain", img: "⏭️" },
      { jp: "先月", kana: "せんげつ", romaji: "sengetsu", fr: "le mois dernier", img: "⏮️" },
      { jp: "年", kana: "とし", romaji: "toshi", fr: "année", img: "📅" },
      { jp: "今年", kana: "ことし", romaji: "kotoshi", fr: "cette année", img: "🗓️" },
      { jp: "来年", kana: "らいねん", romaji: "rainen", fr: "l'année prochaine", img: "⏭️" },
      { jp: "去年", kana: "きょねん", romaji: "kyonen", fr: "l'année dernière", img: "⏮️" },
      { jp: "時間", kana: "じかん", romaji: "jikan", fr: "temps / heure", img: "⏳" },
      { jp: "時", kana: "じ", romaji: "ji", fr: "heure (o'clock)", img: "🕐" },
      { jp: "分", kana: "ふん", romaji: "fun", fr: "minute", img: "⏱️" },
      { jp: "秒", kana: "びょう", romaji: "byō", fr: "seconde", img: "⏲️" },
      { jp: "一時", kana: "いちじ", romaji: "ichiji", fr: "une heure", img: "🕐" },
      { jp: "半", kana: "はん", romaji: "han", fr: "et demie", img: "🕜" },
      { jp: "何時", kana: "なんじ", romaji: "nanji", fr: "quelle heure", img: "❓" },
      { jp: "誕生日", kana: "たんじょうび", romaji: "tanjōbi", fr: "anniversaire", img: "🎂" },
      { jp: "春", kana: "はる", romaji: "haru", fr: "printemps", img: "🌸" },
      { jp: "夏", kana: "なつ", romaji: "natsu", fr: "été", img: "☀️" },
      { jp: "秋", kana: "あき", romaji: "aki", fr: "automne", img: "🍁" },
      { jp: "冬", kana: "ふゆ", romaji: "fuyu", fr: "hiver", img: "❄️" },
      { jp: "季節", kana: "きせつ", romaji: "kisetsu", fr: "saison", img: "🍃" },
      { jp: "休み", kana: "やすみ", romaji: "yasumi", fr: "congé / repos", img: "🏖️" },
      { jp: "予定", kana: "よてい", romaji: "yotei", fr: "projet / planning", img: "📋" },
    ],
  },
  {
    theme: "Famille",
    icon: "👨‍👩‍👧‍👦",
    mots: [
      { jp: "家族", kana: "かぞく", romaji: "kazoku", fr: "famille", img: "👪" },
      { jp: "両親", kana: "りょうしん", romaji: "ryōshin", fr: "les parents", img: "👨‍👩‍👦" },
      { jp: "父", kana: "ちち", romaji: "chichi", fr: "mon père", img: "👨" },
      { jp: "母", kana: "はは", romaji: "haha", fr: "ma mère", img: "👩" },
      { jp: "お父さん", kana: "おとうさん", romaji: "otōsan", fr: "père (poli)", img: "👨" },
      { jp: "お母さん", kana: "おかあさん", romaji: "okāsan", fr: "mère (poli)", img: "👩" },
      { jp: "兄", kana: "あに", romaji: "ani", fr: "mon grand frère", img: "👦" },
      { jp: "姉", kana: "あね", romaji: "ane", fr: "ma grande sœur", img: "👧" },
      { jp: "お兄さん", kana: "おにいさん", romaji: "onīsan", fr: "grand frère (poli)", img: "🧑" },
      { jp: "お姉さん", kana: "おねえさん", romaji: "onēsan", fr: "grande sœur (poli)", img: "👩" },
      { jp: "弟", kana: "おとうと", romaji: "otōto", fr: "petit frère", img: "🧒" },
      { jp: "妹", kana: "いもうと", romaji: "imōto", fr: "petite sœur", img: "👧" },
      { jp: "兄弟", kana: "きょうだい", romaji: "kyōdai", fr: "frères et sœurs", img: "👫" },
      { jp: "姉妹", kana: "しまい", romaji: "shimai", fr: "sœurs", img: "👭" },
      { jp: "子供", kana: "こども", romaji: "kodomo", fr: "enfant", img: "🧒" },
      { jp: "息子", kana: "むすこ", romaji: "musuko", fr: "fils", img: "👦" },
      { jp: "娘", kana: "むすめ", romaji: "musume", fr: "fille (enfant)", img: "👧" },
      { jp: "赤ちゃん", kana: "あかちゃん", romaji: "akachan", fr: "bébé", img: "👶" },
      { jp: "祖父", kana: "そふ", romaji: "sofu", fr: "mon grand-père", img: "👴" },
      { jp: "祖母", kana: "そぼ", romaji: "sobo", fr: "ma grand-mère", img: "👵" },
      { jp: "おじいさん", kana: "おじいさん", romaji: "ojīsan", fr: "grand-père (poli)", img: "👴" },
      { jp: "おばあさん", kana: "おばあさん", romaji: "obāsan", fr: "grand-mère (poli)", img: "👵" },
      { jp: "孫", kana: "まご", romaji: "mago", fr: "petit-enfant", img: "👶" },
      { jp: "おじ", kana: "おじ", romaji: "oji", fr: "oncle", img: "🧔" },
      { jp: "おば", kana: "おば", romaji: "oba", fr: "tante", img: "👩" },
      { jp: "いとこ", kana: "いとこ", romaji: "itoko", fr: "cousin(e)", img: "🧑" },
      { jp: "甥", kana: "おい", romaji: "oi", fr: "neveu", img: "👦" },
      { jp: "姪", kana: "めい", romaji: "mei", fr: "nièce", img: "👧" },
      { jp: "夫", kana: "おっと", romaji: "otto", fr: "mari", img: "🤵" },
      { jp: "妻", kana: "つま", romaji: "tsuma", fr: "épouse", img: "👰" },
      { jp: "主人", kana: "しゅじん", romaji: "shujin", fr: "mon mari", img: "🤵" },
      { jp: "家内", kana: "かない", romaji: "kanai", fr: "mon épouse", img: "👰" },
      { jp: "旦那さん", kana: "だんなさん", romaji: "dannasan", fr: "mari (d'autrui)", img: "🤵" },
      { jp: "奥さん", kana: "おくさん", romaji: "okusan", fr: "épouse (d'autrui)", img: "👰" },
      { jp: "夫婦", kana: "ふうふ", romaji: "fūfu", fr: "couple marié", img: "💑" },
      { jp: "親", kana: "おや", romaji: "oya", fr: "parent", img: "👨‍👧" },
      { jp: "親戚", kana: "しんせき", romaji: "shinseki", fr: "parenté / proches", img: "👪" },
      { jp: "家庭", kana: "かてい", romaji: "katei", fr: "foyer", img: "🏠" },
      { jp: "名字", kana: "みょうじ", romaji: "myōji", fr: "nom de famille", img: "🪪" },
      { jp: "名前", kana: "なまえ", romaji: "namae", fr: "prénom / nom", img: "🏷️" },
      { jp: "大人", kana: "おとな", romaji: "otona", fr: "adulte", img: "🧑" },
      { jp: "男の子", kana: "おとこのこ", romaji: "otoko no ko", fr: "garçon", img: "👦" },
      { jp: "女の子", kana: "おんなのこ", romaji: "onna no ko", fr: "fille (jeune)", img: "👧" },
      { jp: "男の人", kana: "おとこのひと", romaji: "otoko no hito", fr: "homme", img: "👨" },
      { jp: "女の人", kana: "おんなのひと", romaji: "onna no hito", fr: "femme", img: "👩" },
      { jp: "双子", kana: "ふたご", romaji: "futago", fr: "jumeaux", img: "👯" },
      { jp: "長男", kana: "ちょうなん", romaji: "chōnan", fr: "fils aîné", img: "👦" },
      { jp: "長女", kana: "ちょうじょ", romaji: "chōjo", fr: "fille aînée", img: "👧" },
      { jp: "義母", kana: "ぎぼ", romaji: "gibo", fr: "belle-mère", img: "👩" },
      { jp: "義父", kana: "ぎふ", romaji: "gifu", fr: "beau-père", img: "👨" },
    ],
  },
  {
    theme: "Le corps",
    icon: "🧍",
    mots: [
      { jp: "体", kana: "からだ", romaji: "karada", fr: "corps", img: "🧍" },
      { jp: "頭", kana: "あたま", romaji: "atama", fr: "tête", img: "🗣️" },
      { jp: "顔", kana: "かお", romaji: "kao", fr: "visage", img: "😊" },
      { jp: "髪", kana: "かみ", romaji: "kami", fr: "cheveux", img: "💇" },
      { jp: "目", kana: "め", romaji: "me", fr: "œil", img: "👁️" },
      { jp: "耳", kana: "みみ", romaji: "mimi", fr: "oreille", img: "👂" },
      { jp: "鼻", kana: "はな", romaji: "hana", fr: "nez", img: "👃" },
      { jp: "口", kana: "くち", romaji: "kuchi", fr: "bouche", img: "👄" },
      { jp: "歯", kana: "は", romaji: "ha", fr: "dent", img: "🦷" },
      { jp: "舌", kana: "した", romaji: "shita", fr: "langue", img: "👅" },
      { jp: "唇", kana: "くちびる", romaji: "kuchibiru", fr: "lèvres", img: "💋" },
      { jp: "首", kana: "くび", romaji: "kubi", fr: "cou", img: "🧣" },
      { jp: "喉", kana: "のど", romaji: "nodo", fr: "gorge", img: "🗣️" },
      { jp: "肩", kana: "かた", romaji: "kata", fr: "épaule", img: "💪" },
      { jp: "腕", kana: "うで", romaji: "ude", fr: "bras", img: "💪" },
      { jp: "肘", kana: "ひじ", romaji: "hiji", fr: "coude", img: "💪" },
      { jp: "手", kana: "て", romaji: "te", fr: "main", img: "✋" },
      { jp: "指", kana: "ゆび", romaji: "yubi", fr: "doigt", img: "👆" },
      { jp: "爪", kana: "つめ", romaji: "tsume", fr: "ongle", img: "💅" },
      { jp: "手首", kana: "てくび", romaji: "tekubi", fr: "poignet", img: "⌚" },
      { jp: "胸", kana: "むね", romaji: "mune", fr: "poitrine", img: "🫁" },
      { jp: "背中", kana: "せなか", romaji: "senaka", fr: "dos", img: "🔙" },
      { jp: "腰", kana: "こし", romaji: "koshi", fr: "hanches / reins", img: "🕺" },
      { jp: "お腹", kana: "おなか", romaji: "onaka", fr: "ventre", img: "🤰" },
      { jp: "足", kana: "あし", romaji: "ashi", fr: "pied / jambe", img: "🦵" },
      { jp: "膝", kana: "ひざ", romaji: "hiza", fr: "genou", img: "🦵" },
      { jp: "足首", kana: "あしくび", romaji: "ashikubi", fr: "cheville", img: "🦶" },
      { jp: "かかと", kana: "かかと", romaji: "kakato", fr: "talon", img: "🦶" },
      { jp: "つま先", kana: "つまさき", romaji: "tsumasaki", fr: "orteil", img: "🦶" },
      { jp: "皮膚", kana: "ひふ", romaji: "hifu", fr: "peau", img: "🖐️" },
      { jp: "骨", kana: "ほね", romaji: "hone", fr: "os", img: "🦴" },
      { jp: "血", kana: "ち", romaji: "chi", fr: "sang", img: "🩸" },
      { jp: "心臓", kana: "しんぞう", romaji: "shinzō", fr: "cœur (organe)", img: "🫀" },
      { jp: "脳", kana: "のう", romaji: "nō", fr: "cerveau", img: "🧠" },
      { jp: "肺", kana: "はい", romaji: "hai", fr: "poumon", img: "🫁" },
      { jp: "胃", kana: "い", romaji: "i", fr: "estomac", img: "🩺" },
      { jp: "筋肉", kana: "きんにく", romaji: "kinniku", fr: "muscle", img: "💪" },
      { jp: "声", kana: "こえ", romaji: "koe", fr: "voix", img: "🗣️" },
      { jp: "涙", kana: "なみだ", romaji: "namida", fr: "larme", img: "😢" },
      { jp: "汗", kana: "あせ", romaji: "ase", fr: "sueur", img: "💦" },
      { jp: "息", kana: "いき", romaji: "iki", fr: "souffle", img: "😤" },
      { jp: "眉毛", kana: "まゆげ", romaji: "mayuge", fr: "sourcil", img: "🤨" },
      { jp: "まつげ", kana: "まつげ", romaji: "matsuge", fr: "cil", img: "👁️" },
      { jp: "ほお", kana: "ほお", romaji: "hoo", fr: "joue", img: "😊" },
      { jp: "あご", kana: "あご", romaji: "ago", fr: "menton", img: "🧔" },
      { jp: "太もも", kana: "ふともも", romaji: "futomomo", fr: "cuisse", img: "🦵" },
      { jp: "手のひら", kana: "てのひら", romaji: "tenohira", fr: "paume", img: "🖐️" },
      { jp: "指先", kana: "ゆびさき", romaji: "yubisaki", fr: "bout du doigt", img: "👆" },
      { jp: "体重", kana: "たいじゅう", romaji: "taijū", fr: "poids (du corps)", img: "⚖️" },
      { jp: "身長", kana: "しんちょう", romaji: "shinchō", fr: "taille (hauteur)", img: "📏" },
    ],
  },
  {
    theme: "Couleurs",
    icon: "🎨",
    mots: [
      { jp: "色", kana: "いろ", romaji: "iro", fr: "couleur", img: "🎨" },
      { jp: "赤", kana: "あか", romaji: "aka", fr: "rouge", img: "🔴" },
      { jp: "青", kana: "あお", romaji: "ao", fr: "bleu", img: "🔵" },
      { jp: "黄色", kana: "きいろ", romaji: "kiiro", fr: "jaune", img: "🟡" },
      { jp: "緑", kana: "みどり", romaji: "midori", fr: "vert", img: "🟢" },
      { jp: "白", kana: "しろ", romaji: "shiro", fr: "blanc", img: "⚪" },
      { jp: "黒", kana: "くろ", romaji: "kuro", fr: "noir", img: "⚫" },
      { jp: "茶色", kana: "ちゃいろ", romaji: "chairo", fr: "marron", img: "🟤" },
      { jp: "紫", kana: "むらさき", romaji: "murasaki", fr: "violet", img: "🟣" },
      { jp: "ピンク", kana: "ピンク", romaji: "pinku", fr: "rose", img: "🌸" },
      { jp: "オレンジ", kana: "オレンジ", romaji: "orenji", fr: "orange", img: "🟠" },
      { jp: "灰色", kana: "はいいろ", romaji: "haiiro", fr: "gris", img: "⬜" },
      { jp: "金色", kana: "きんいろ", romaji: "kin'iro", fr: "doré", img: "🥇" },
      { jp: "銀色", kana: "ぎんいろ", romaji: "gin'iro", fr: "argenté", img: "🥈" },
      { jp: "水色", kana: "みずいろ", romaji: "mizuiro", fr: "bleu clair", img: "💧" },
      { jp: "紺色", kana: "こんいろ", romaji: "kon'iro", fr: "bleu marine", img: "🔵" },
      { jp: "空色", kana: "そらいろ", romaji: "sorairo", fr: "bleu ciel", img: "🌤️" },
      { jp: "黄緑", kana: "きみどり", romaji: "kimidori", fr: "vert clair", img: "🟢" },
      { jp: "濃い", kana: "こい", romaji: "koi", fr: "foncé", img: "🌑" },
      { jp: "薄い", kana: "うすい", romaji: "usui", fr: "pâle (clair)", img: "🌕" },
      { jp: "明るい色", kana: "あかるいいろ", romaji: "akarui iro", fr: "couleur vive", img: "💡" },
      { jp: "暗い色", kana: "くらいいろ", romaji: "kurai iro", fr: "couleur sombre", img: "🌚" },
      { jp: "赤い", kana: "あかい", romaji: "akai", fr: "rouge (adjectif)", img: "🍎" },
      { jp: "青い", kana: "あおい", romaji: "aoi", fr: "bleu (adjectif)", img: "🫐" },
      { jp: "白い", kana: "しろい", romaji: "shiroi", fr: "blanc (adjectif)", img: "🕊️" },
      { jp: "黒い", kana: "くろい", romaji: "kuroi", fr: "noir (adjectif)", img: "🖤" },
      { jp: "黄色い", kana: "きいろい", romaji: "kiiroi", fr: "jaune (adjectif)", img: "🌻" },
      { jp: "茶色い", kana: "ちゃいろい", romaji: "chairoi", fr: "brun (adjectif)", img: "🐻" },
      { jp: "ベージュ", kana: "ベージュ", romaji: "bēju", fr: "beige", img: "🟫" },
      { jp: "クリーム色", kana: "クリームいろ", romaji: "kurīmuiro", fr: "crème", img: "🍦" },
      { jp: "肌色", kana: "はだいろ", romaji: "hadairo", fr: "couleur chair", img: "🤲" },
      { jp: "桃色", kana: "ももいろ", romaji: "momoiro", fr: "rose pêche", img: "🍑" },
      { jp: "赤紫", kana: "あかむらさき", romaji: "akamurasaki", fr: "magenta", img: "🟣" },
      { jp: "青紫", kana: "あおむらさき", romaji: "aomurasaki", fr: "indigo", img: "🔵" },
      { jp: "黄金色", kana: "こがねいろ", romaji: "koganeiro", fr: "couleur or", img: "✨" },
      { jp: "銀", kana: "ぎん", romaji: "gin", fr: "argent", img: "🥈" },
      { jp: "金", kana: "きん", romaji: "kin", fr: "or", img: "🥇" },
      { jp: "虹色", kana: "にじいろ", romaji: "nijiiro", fr: "couleur arc-en-ciel", img: "🌈" },
      { jp: "透明", kana: "とうめい", romaji: "tōmei", fr: "transparent", img: "🫥" },
      { jp: "カラフル", kana: "カラフル", romaji: "karafuru", fr: "coloré", img: "🎨" },
      { jp: "深緑", kana: "ふかみどり", romaji: "fukamidori", fr: "vert foncé", img: "🌲" },
      { jp: "若草色", kana: "わかくさいろ", romaji: "wakakusairo", fr: "vert tendre", img: "🌱" },
      { jp: "えんじ色", kana: "えんじいろ", romaji: "enjiiro", fr: "bordeaux", img: "🍷" },
      { jp: "山吹色", kana: "やまぶきいろ", romaji: "yamabukiiro", fr: "jaune d'or", img: "🌼" },
      { jp: "灰", kana: "はい", romaji: "hai", fr: "cendre (gris)", img: "🌫️" },
      { jp: "コバルトブルー", kana: "コバルトブルー", romaji: "kobaruto burū", fr: "bleu cobalt", img: "🔷" },
      { jp: "ワインレッド", kana: "ワインレッド", romaji: "wain reddo", fr: "rouge vin", img: "🍷" },
      { jp: "抹茶色", kana: "まっちゃいろ", romaji: "matchairo", fr: "vert matcha", img: "🍵" },
      { jp: "桜色", kana: "さくらいろ", romaji: "sakurairo", fr: "rose sakura", img: "🌸" },
      { jp: "単色", kana: "たんしょく", romaji: "tanshoku", fr: "monochrome", img: "◼️" },
    ],
  },
  {
    theme: "Alimentation",
    icon: "🍱",
    mots: [
      { jp: "食べ物", kana: "たべもの", romaji: "tabemono", fr: "nourriture", img: "🍱" },
      { jp: "飲み物", kana: "のみもの", romaji: "nomimono", fr: "boisson", img: "🥤" },
      { jp: "ご飯", kana: "ごはん", romaji: "gohan", fr: "riz / repas", img: "🍚" },
      { jp: "米", kana: "こめ", romaji: "kome", fr: "riz (cru)", img: "🌾" },
      { jp: "パン", kana: "パン", romaji: "pan", fr: "pain", img: "🍞" },
      { jp: "麺", kana: "めん", romaji: "men", fr: "nouilles", img: "🍜" },
      { jp: "うどん", kana: "うどん", romaji: "udon", fr: "udon", img: "🍲" },
      { jp: "そば", kana: "そば", romaji: "soba", fr: "soba", img: "🥢" },
      { jp: "ラーメン", kana: "ラーメン", romaji: "rāmen", fr: "ramen", img: "🍜" },
      { jp: "寿司", kana: "すし", romaji: "sushi", fr: "sushi", img: "🍣" },
      { jp: "刺身", kana: "さしみ", romaji: "sashimi", fr: "sashimi", img: "🐟" },
      { jp: "天ぷら", kana: "てんぷら", romaji: "tenpura", fr: "tempura", img: "🍤" },
      { jp: "味噌汁", kana: "みそしる", romaji: "misoshiru", fr: "soupe miso", img: "🍲" },
      { jp: "肉", kana: "にく", romaji: "niku", fr: "viande", img: "🍖" },
      { jp: "牛肉", kana: "ぎゅうにく", romaji: "gyūniku", fr: "bœuf", img: "🥩" },
      { jp: "豚肉", kana: "ぶたにく", romaji: "butaniku", fr: "porc", img: "🥓" },
      { jp: "鶏肉", kana: "とりにく", romaji: "toriniku", fr: "poulet", img: "🍗" },
      { jp: "魚", kana: "さかな", romaji: "sakana", fr: "poisson", img: "🐟" },
      { jp: "卵", kana: "たまご", romaji: "tamago", fr: "œuf", img: "🥚" },
      { jp: "野菜", kana: "やさい", romaji: "yasai", fr: "légumes", img: "🥬" },
      { jp: "果物", kana: "くだもの", romaji: "kudamono", fr: "fruits", img: "🍎" },
      { jp: "りんご", kana: "りんご", romaji: "ringo", fr: "pomme", img: "🍎" },
      { jp: "みかん", kana: "みかん", romaji: "mikan", fr: "mandarine", img: "🍊" },
      { jp: "バナナ", kana: "バナナ", romaji: "banana", fr: "banane", img: "🍌" },
      { jp: "いちご", kana: "いちご", romaji: "ichigo", fr: "fraise", img: "🍓" },
      { jp: "ぶどう", kana: "ぶどう", romaji: "budō", fr: "raisin", img: "🍇" },
      { jp: "スイカ", kana: "スイカ", romaji: "suika", fr: "pastèque", img: "🍉" },
      { jp: "トマト", kana: "トマト", romaji: "tomato", fr: "tomate", img: "🍅" },
      { jp: "じゃがいも", kana: "じゃがいも", romaji: "jagaimo", fr: "pomme de terre", img: "🥔" },
      { jp: "にんじん", kana: "にんじん", romaji: "ninjin", fr: "carotte", img: "🥕" },
      { jp: "玉ねぎ", kana: "たまねぎ", romaji: "tamanegi", fr: "oignon", img: "🧅" },
      { jp: "きゅうり", kana: "きゅうり", romaji: "kyūri", fr: "concombre", img: "🥒" },
      { jp: "豆腐", kana: "とうふ", romaji: "tōfu", fr: "tofu", img: "🍥" },
      { jp: "納豆", kana: "なっとう", romaji: "nattō", fr: "nattō", img: "🫘" },
      { jp: "チーズ", kana: "チーズ", romaji: "chīzu", fr: "fromage", img: "🧀" },
      { jp: "牛乳", kana: "ぎゅうにゅう", romaji: "gyūnyū", fr: "lait", img: "🥛" },
      { jp: "水", kana: "みず", romaji: "mizu", fr: "eau", img: "💧" },
      { jp: "お茶", kana: "おちゃ", romaji: "ocha", fr: "thé", img: "🍵" },
      { jp: "コーヒー", kana: "コーヒー", romaji: "kōhī", fr: "café", img: "☕" },
      { jp: "ジュース", kana: "ジュース", romaji: "jūsu", fr: "jus", img: "🧃" },
      { jp: "ビール", kana: "ビール", romaji: "bīru", fr: "bière", img: "🍺" },
      { jp: "お酒", kana: "おさけ", romaji: "osake", fr: "alcool / saké", img: "🍶" },
      { jp: "砂糖", kana: "さとう", romaji: "satō", fr: "sucre", img: "🧂" },
      { jp: "塩", kana: "しお", romaji: "shio", fr: "sel", img: "🧂" },
      { jp: "醤油", kana: "しょうゆ", romaji: "shōyu", fr: "sauce soja", img: "🍶" },
      { jp: "油", kana: "あぶら", romaji: "abura", fr: "huile", img: "🛢️" },
      { jp: "お菓子", kana: "おかし", romaji: "okashi", fr: "friandise", img: "🍬" },
      { jp: "ケーキ", kana: "ケーキ", romaji: "kēki", fr: "gâteau", img: "🍰" },
      { jp: "アイスクリーム", kana: "アイスクリーム", romaji: "aisukurīmu", fr: "glace", img: "🍨" },
      { jp: "チョコレート", kana: "チョコレート", romaji: "chokorēto", fr: "chocolat", img: "🍫" },
    ],
  },
  {
    theme: "Restauration",
    icon: "🍽️",
    mots: [
      { jp: "レストラン", kana: "レストラン", romaji: "resutoran", fr: "restaurant", img: "🍽️" },
      { jp: "食堂", kana: "しょくどう", romaji: "shokudō", fr: "cantine / réfectoire", img: "🍲" },
      { jp: "喫茶店", kana: "きっさてん", romaji: "kissaten", fr: "café (salon de thé)", img: "☕" },
      { jp: "居酒屋", kana: "いざかや", romaji: "izakaya", fr: "taverne (izakaya)", img: "🍶" },
      { jp: "メニュー", kana: "メニュー", romaji: "menyū", fr: "menu (carte)", img: "📋" },
      { jp: "注文", kana: "ちゅうもん", romaji: "chūmon", fr: "commande", img: "📝" },
      { jp: "予約", kana: "よやく", romaji: "yoyaku", fr: "réservation", img: "📅" },
      { jp: "席", kana: "せき", romaji: "seki", fr: "place / siège", img: "💺" },
      { jp: "お勘定", kana: "おかんじょう", romaji: "okanjō", fr: "l'addition", img: "🧾" },
      { jp: "会計", kana: "かいけい", romaji: "kaikei", fr: "la caisse (paiement)", img: "💰" },
      { jp: "レシート", kana: "レシート", romaji: "reshīto", fr: "ticket de caisse", img: "🧾" },
      { jp: "チップ", kana: "チップ", romaji: "chippu", fr: "pourboire", img: "💵" },
      { jp: "箸", kana: "はし", romaji: "hashi", fr: "baguettes", img: "🥢" },
      { jp: "スプーン", kana: "スプーン", romaji: "supūn", fr: "cuillère", img: "🥄" },
      { jp: "フォーク", kana: "フォーク", romaji: "fōku", fr: "fourchette", img: "🍴" },
      { jp: "ナイフ", kana: "ナイフ", romaji: "naifu", fr: "couteau", img: "🔪" },
      { jp: "お皿", kana: "おさら", romaji: "osara", fr: "assiette", img: "🍽️" },
      { jp: "茶碗", kana: "ちゃわん", romaji: "chawan", fr: "bol (à riz)", img: "🍚" },
      { jp: "コップ", kana: "コップ", romaji: "koppu", fr: "verre (gobelet)", img: "🥛" },
      { jp: "グラス", kana: "グラス", romaji: "gurasu", fr: "verre (à pied)", img: "🍷" },
      { jp: "おしぼり", kana: "おしぼり", romaji: "oshibori", fr: "serviette humide", img: "🧻" },
      { jp: "ナプキン", kana: "ナプキン", romaji: "napukin", fr: "serviette de table", img: "🍽️" },
      { jp: "定食", kana: "ていしょく", romaji: "teishoku", fr: "menu complet", img: "🍱" },
      { jp: "前菜", kana: "ぜんさい", romaji: "zensai", fr: "entrée", img: "🥗" },
      { jp: "主菜", kana: "しゅさい", romaji: "shusai", fr: "plat principal", img: "🍛" },
      { jp: "デザート", kana: "デザート", romaji: "dezāto", fr: "dessert", img: "🍮" },
      { jp: "おかわり", kana: "おかわり", romaji: "okawari", fr: "se resservir", img: "🍚" },
      { jp: "大盛り", kana: "おおもり", romaji: "ōmori", fr: "grande portion", img: "🍜" },
      { jp: "持ち帰り", kana: "もちかえり", romaji: "mochikaeri", fr: "à emporter", img: "🥡" },
      { jp: "店内", kana: "てんない", romaji: "tennai", fr: "sur place", img: "🪑" },
      { jp: "満席", kana: "まんせき", romaji: "manseki", fr: "complet (plein)", img: "🚫" },
      { jp: "空席", kana: "くうせき", romaji: "kūseki", fr: "place libre", img: "🪑" },
      { jp: "店員", kana: "てんいん", romaji: "ten'in", fr: "serveur / vendeur", img: "🧑‍🍳" },
      { jp: "料理", kana: "りょうり", romaji: "ryōri", fr: "plat / cuisine", img: "🍲" },
      { jp: "味", kana: "あじ", romaji: "aji", fr: "goût", img: "👅" },
      { jp: "美味しい", kana: "おいしい", romaji: "oishii", fr: "délicieux", img: "😋" },
      { jp: "まずい", kana: "まずい", romaji: "mazui", fr: "mauvais (goût)", img: "🤢" },
      { jp: "甘い", kana: "あまい", romaji: "amai", fr: "sucré", img: "🍬" },
      { jp: "辛い", kana: "からい", romaji: "karai", fr: "épicé / piquant", img: "🌶️" },
      { jp: "塩辛い", kana: "しおからい", romaji: "shiokarai", fr: "salé", img: "🧂" },
      { jp: "苦い", kana: "にがい", romaji: "nigai", fr: "amer", img: "☕" },
      { jp: "酸っぱい", kana: "すっぱい", romaji: "suppai", fr: "acide", img: "🍋" },
      { jp: "熱い", kana: "あつい", romaji: "atsui", fr: "chaud (à manger)", img: "🔥" },
      { jp: "冷たい", kana: "つめたい", romaji: "tsumetai", fr: "froid (à boire)", img: "🧊" },
      { jp: "乾杯", kana: "かんぱい", romaji: "kanpai", fr: "santé ! (trinquer)", img: "🍻" },
      { jp: "おすすめ", kana: "おすすめ", romaji: "osusume", fr: "la recommandation", img: "👍" },
      { jp: "セット", kana: "セット", romaji: "setto", fr: "formule (set)", img: "🍔" },
      { jp: "飲み放題", kana: "のみほうだい", romaji: "nomihōdai", fr: "boissons à volonté", img: "🍺" },
      { jp: "食べ放題", kana: "たべほうだい", romaji: "tabehōdai", fr: "buffet à volonté", img: "🍽️" },
      { jp: "お冷", kana: "おひや", romaji: "ohiya", fr: "eau fraîche (au resto)", img: "💧" },
    ],
  },
  {
    theme: "Achats & argent",
    icon: "🛍️",
    mots: [
      { jp: "買い物", kana: "かいもの", romaji: "kaimono", fr: "achats / shopping", img: "🛍️" },
      { jp: "店", kana: "みせ", romaji: "mise", fr: "magasin", img: "🏪" },
      { jp: "お店", kana: "おみせ", romaji: "omise", fr: "boutique", img: "🏬" },
      { jp: "スーパー", kana: "スーパー", romaji: "sūpā", fr: "supermarché", img: "🛒" },
      { jp: "デパート", kana: "デパート", romaji: "depāto", fr: "grand magasin", img: "🏬" },
      { jp: "コンビニ", kana: "コンビニ", romaji: "konbini", fr: "supérette", img: "🏪" },
      { jp: "市場", kana: "いちば", romaji: "ichiba", fr: "marché", img: "🧺" },
      { jp: "商店街", kana: "しょうてんがい", romaji: "shōtengai", fr: "rue commerçante", img: "🏙️" },
      { jp: "お金", kana: "おかね", romaji: "okane", fr: "argent", img: "💰" },
      { jp: "円", kana: "えん", romaji: "en", fr: "yen", img: "💴" },
      { jp: "ドル", kana: "ドル", romaji: "doru", fr: "dollar", img: "💵" },
      { jp: "ユーロ", kana: "ユーロ", romaji: "yūro", fr: "euro", img: "💶" },
      { jp: "現金", kana: "げんきん", romaji: "genkin", fr: "espèces", img: "💵" },
      { jp: "小銭", kana: "こぜに", romaji: "kozeni", fr: "monnaie (pièces)", img: "🪙" },
      { jp: "お札", kana: "おさつ", romaji: "osatsu", fr: "billet", img: "💴" },
      { jp: "硬貨", kana: "こうか", romaji: "kōka", fr: "pièce de monnaie", img: "🪙" },
      { jp: "財布", kana: "さいふ", romaji: "saifu", fr: "portefeuille", img: "👛" },
      { jp: "カード", kana: "カード", romaji: "kādo", fr: "carte (bancaire)", img: "💳" },
      { jp: "クレジットカード", kana: "クレジットカード", romaji: "kurejitto kādo", fr: "carte de crédit", img: "💳" },
      { jp: "レジ", kana: "レジ", romaji: "reji", fr: "caisse", img: "🧾" },
      { jp: "値段", kana: "ねだん", romaji: "nedan", fr: "prix", img: "🔖" },
      { jp: "価格", kana: "かかく", romaji: "kakaku", fr: "tarif", img: "🏷️" },
      { jp: "高い", kana: "たかい", romaji: "takai", fr: "cher", img: "💸" },
      { jp: "安い", kana: "やすい", romaji: "yasui", fr: "bon marché", img: "🏷️" },
      { jp: "無料", kana: "むりょう", romaji: "muryō", fr: "gratuit", img: "🆓" },
      { jp: "有料", kana: "ゆうりょう", romaji: "yūryō", fr: "payant", img: "💰" },
      { jp: "割引", kana: "わりびき", romaji: "waribiki", fr: "réduction", img: "🔻" },
      { jp: "セール", kana: "セール", romaji: "sēru", fr: "soldes", img: "🏷️" },
      { jp: "特価", kana: "とっか", romaji: "tokka", fr: "prix spécial", img: "✨" },
      { jp: "買う", kana: "かう", romaji: "kau", fr: "acheter", img: "🛒" },
      { jp: "売る", kana: "うる", romaji: "uru", fr: "vendre", img: "💱" },
      { jp: "払う", kana: "はらう", romaji: "harau", fr: "payer", img: "💳" },
      { jp: "おつり", kana: "おつり", romaji: "otsuri", fr: "monnaie rendue", img: "🪙" },
      { jp: "領収書", kana: "りょうしゅうしょ", romaji: "ryōshūsho", fr: "reçu / facture", img: "🧾" },
      { jp: "袋", kana: "ふくろ", romaji: "fukuro", fr: "sac", img: "🛍️" },
      { jp: "レジ袋", kana: "レジぶくろ", romaji: "rejibukuro", fr: "sac plastique", img: "🛍️" },
      { jp: "商品", kana: "しょうひん", romaji: "shōhin", fr: "marchandise", img: "📦" },
      { jp: "品物", kana: "しなもの", romaji: "shinamono", fr: "article", img: "📦" },
      { jp: "在庫", kana: "ざいこ", romaji: "zaiko", fr: "stock", img: "📦" },
      { jp: "売り切れ", kana: "うりきれ", romaji: "urikire", fr: "épuisé (stock)", img: "🚫" },
      { jp: "新品", kana: "しんぴん", romaji: "shinpin", fr: "neuf (produit)", img: "✨" },
      { jp: "中古", kana: "ちゅうこ", romaji: "chūko", fr: "d'occasion", img: "♻️" },
      { jp: "返品", kana: "へんぴん", romaji: "henpin", fr: "retour (article)", img: "🔙" },
      { jp: "交換", kana: "こうかん", romaji: "kōkan", fr: "échange", img: "🔄" },
      { jp: "税金", kana: "ぜいきん", romaji: "zeikin", fr: "taxe / impôt", img: "🧮" },
      { jp: "消費税", kana: "しょうひぜい", romaji: "shōhizei", fr: "TVA (taxe conso)", img: "🧾" },
      { jp: "予算", kana: "よさん", romaji: "yosan", fr: "budget", img: "📊" },
      { jp: "貯金", kana: "ちょきん", romaji: "chokin", fr: "épargne", img: "🐖" },
      { jp: "銀行", kana: "ぎんこう", romaji: "ginkō", fr: "banque", img: "🏦" },
      { jp: "現金自動預け払い機", kana: "げんきんじどうあずけばらいき", romaji: "ATM", fr: "distributeur (DAB)", img: "🏧" },
    ],
  },
  {
    theme: "Transport",
    icon: "🚃",
    mots: [
      { jp: "交通", kana: "こうつう", romaji: "kōtsū", fr: "transport / circulation", img: "🚦" },
      { jp: "電車", kana: "でんしゃ", romaji: "densha", fr: "train", img: "🚃" },
      { jp: "新幹線", kana: "しんかんせん", romaji: "shinkansen", fr: "train à grande vitesse", img: "🚄" },
      { jp: "地下鉄", kana: "ちかてつ", romaji: "chikatetsu", fr: "métro", img: "🚇" },
      { jp: "バス", kana: "バス", romaji: "basu", fr: "bus", img: "🚌" },
      { jp: "車", kana: "くるま", romaji: "kuruma", fr: "voiture", img: "🚗" },
      { jp: "タクシー", kana: "タクシー", romaji: "takushī", fr: "taxi", img: "🚕" },
      { jp: "自転車", kana: "じてんしゃ", romaji: "jitensha", fr: "vélo", img: "🚲" },
      { jp: "バイク", kana: "バイク", romaji: "baiku", fr: "moto", img: "🏍️" },
      { jp: "飛行機", kana: "ひこうき", romaji: "hikōki", fr: "avion", img: "✈️" },
      { jp: "船", kana: "ふね", romaji: "fune", fr: "bateau", img: "🚢" },
      { jp: "フェリー", kana: "フェリー", romaji: "ferī", fr: "ferry", img: "⛴️" },
      { jp: "トラック", kana: "トラック", romaji: "torakku", fr: "camion", img: "🚚" },
      { jp: "救急車", kana: "きゅうきゅうしゃ", romaji: "kyūkyūsha", fr: "ambulance", img: "🚑" },
      { jp: "消防車", kana: "しょうぼうしゃ", romaji: "shōbōsha", fr: "camion de pompiers", img: "🚒" },
      { jp: "パトカー", kana: "パトカー", romaji: "patokā", fr: "voiture de police", img: "🚓" },
      { jp: "駅", kana: "えき", romaji: "eki", fr: "gare / station", img: "🚉" },
      { jp: "バス停", kana: "バスてい", romaji: "basutei", fr: "arrêt de bus", img: "🚏" },
      { jp: "空港", kana: "くうこう", romaji: "kūkō", fr: "aéroport", img: "🛫" },
      { jp: "港", kana: "みなと", romaji: "minato", fr: "port", img: "⚓" },
      { jp: "切符", kana: "きっぷ", romaji: "kippu", fr: "ticket", img: "🎫" },
      { jp: "定期券", kana: "ていきけん", romaji: "teikiken", fr: "abonnement (transport)", img: "🪪" },
      { jp: "改札", kana: "かいさつ", romaji: "kaisatsu", fr: "portillon (contrôle)", img: "🚧" },
      { jp: "ホーム", kana: "ホーム", romaji: "hōmu", fr: "quai", img: "🛤️" },
      { jp: "線路", kana: "せんろ", romaji: "senro", fr: "voie ferrée", img: "🛤️" },
      { jp: "運転", kana: "うんてん", romaji: "unten", fr: "conduite", img: "🚗" },
      { jp: "運転手", kana: "うんてんしゅ", romaji: "untenshu", fr: "chauffeur", img: "🧑‍✈️" },
      { jp: "乗る", kana: "のる", romaji: "noru", fr: "monter (véhicule)", img: "🚶" },
      { jp: "降りる", kana: "おりる", romaji: "oriru", fr: "descendre (véhicule)", img: "🚶" },
      { jp: "乗り換え", kana: "のりかえ", romaji: "norikae", fr: "correspondance", img: "🔄" },
      { jp: "道", kana: "みち", romaji: "michi", fr: "route / chemin", img: "🛣️" },
      { jp: "道路", kana: "どうろ", romaji: "dōro", fr: "route (chaussée)", img: "🛣️" },
      { jp: "高速道路", kana: "こうそくどうろ", romaji: "kōsoku dōro", fr: "autoroute", img: "🛣️" },
      { jp: "信号", kana: "しんごう", romaji: "shingō", fr: "feu de circulation", img: "🚦" },
      { jp: "横断歩道", kana: "おうだんほどう", romaji: "ōdan hodō", fr: "passage piéton", img: "🚸" },
      { jp: "踏切", kana: "ふみきり", romaji: "fumikiri", fr: "passage à niveau", img: "🚧" },
      { jp: "交差点", kana: "こうさてん", romaji: "kōsaten", fr: "carrefour", img: "➕" },
      { jp: "駐車場", kana: "ちゅうしゃじょう", romaji: "chūshajō", fr: "parking", img: "🅿️" },
      { jp: "ガソリンスタンド", kana: "ガソリンスタンド", romaji: "gasorin sutando", fr: "station-service", img: "⛽" },
      { jp: "ガソリン", kana: "ガソリン", romaji: "gasorin", fr: "essence", img: "⛽" },
      { jp: "渋滞", kana: "じゅうたい", romaji: "jūtai", fr: "embouteillage", img: "🚗" },
      { jp: "事故", kana: "じこ", romaji: "jiko", fr: "accident", img: "💥" },
      { jp: "座席", kana: "ざせき", romaji: "zaseki", fr: "siège", img: "💺" },
      { jp: "運賃", kana: "うんちん", romaji: "unchin", fr: "tarif (transport)", img: "💴" },
      { jp: "時刻表", kana: "じこくひょう", romaji: "jikokuhyō", fr: "horaires", img: "🕐" },
      { jp: "遅延", kana: "ちえん", romaji: "chien", fr: "retard", img: "⏰" },
      { jp: "満員", kana: "まんいん", romaji: "man'in", fr: "bondé", img: "🧍" },
      { jp: "出発", kana: "しゅっぱつ", romaji: "shuppatsu", fr: "départ", img: "🛫" },
      { jp: "到着", kana: "とうちゃく", romaji: "tōchaku", fr: "arrivée", img: "🛬" },
      { jp: "ヘルメット", kana: "ヘルメット", romaji: "herumetto", fr: "casque", img: "⛑️" },
    ],
  },
  {
    theme: "Voyages",
    icon: "✈️",
    mots: [
      { jp: "旅行", kana: "りょこう", romaji: "ryokō", fr: "voyage", img: "🧳" },
      { jp: "旅", kana: "たび", romaji: "tabi", fr: "périple", img: "🎒" },
      { jp: "観光", kana: "かんこう", romaji: "kankō", fr: "tourisme", img: "🏯" },
      { jp: "観光客", kana: "かんこうきゃく", romaji: "kankōkyaku", fr: "touriste", img: "📸" },
      { jp: "海外", kana: "かいがい", romaji: "kaigai", fr: "à l'étranger", img: "🌍" },
      { jp: "国内", kana: "こくない", romaji: "kokunai", fr: "national (dans le pays)", img: "🗾" },
      { jp: "空港", kana: "くうこう", romaji: "kūkō", fr: "aéroport", img: "🛫" },
      { jp: "パスポート", kana: "パスポート", romaji: "pasupōto", fr: "passeport", img: "🛂" },
      { jp: "ビザ", kana: "ビザ", romaji: "biza", fr: "visa", img: "📄" },
      { jp: "航空券", kana: "こうくうけん", romaji: "kōkūken", fr: "billet d'avion", img: "🎫" },
      { jp: "荷物", kana: "にもつ", romaji: "nimotsu", fr: "bagages", img: "🧳" },
      { jp: "スーツケース", kana: "スーツケース", romaji: "sūtsukēsu", fr: "valise", img: "🧳" },
      { jp: "リュック", kana: "リュック", romaji: "ryukku", fr: "sac à dos", img: "🎒" },
      { jp: "ホテル", kana: "ホテル", romaji: "hoteru", fr: "hôtel", img: "🏨" },
      { jp: "旅館", kana: "りょかん", romaji: "ryokan", fr: "auberge japonaise", img: "♨️" },
      { jp: "民宿", kana: "みんしゅく", romaji: "minshuku", fr: "chambre d'hôtes", img: "🏡" },
      { jp: "予約", kana: "よやく", romaji: "yoyaku", fr: "réservation (voyage)", img: "📅" },
      { jp: "チェックイン", kana: "チェックイン", romaji: "chekkuin", fr: "enregistrement", img: "🛎️" },
      { jp: "チェックアウト", kana: "チェックアウト", romaji: "chekkuauto", fr: "départ (check-out)", img: "🚪" },
      { jp: "フロント", kana: "フロント", romaji: "furonto", fr: "réception (hôtel)", img: "🛎️" },
      { jp: "部屋", kana: "へや", romaji: "heya", fr: "chambre (d'hôtel)", img: "🛏️" },
      { jp: "地図", kana: "ちず", romaji: "chizu", fr: "carte (plan)", img: "🗺️" },
      { jp: "案内所", kana: "あんないじょ", romaji: "annaijo", fr: "office de tourisme", img: "ℹ️" },
      { jp: "ガイド", kana: "ガイド", romaji: "gaido", fr: "guide (personne)", img: "🧭" },
      { jp: "お土産", kana: "おみやげ", romaji: "omiyage", fr: "souvenir (cadeau)", img: "🎁" },
      { jp: "写真", kana: "しゃしん", romaji: "shashin", fr: "photo", img: "📷" },
      { jp: "カメラ", kana: "カメラ", romaji: "kamera", fr: "appareil photo", img: "📸" },
      { jp: "名所", kana: "めいしょ", romaji: "meisho", fr: "site célèbre", img: "🗼" },
      { jp: "観光地", kana: "かんこうち", romaji: "kankōchi", fr: "lieu touristique", img: "🏝️" },
      { jp: "温泉", kana: "おんせん", romaji: "onsen", fr: "source chaude", img: "♨️" },
      { jp: "城", kana: "しろ", romaji: "shiro", fr: "château", img: "🏯" },
      { jp: "寺", kana: "てら", romaji: "tera", fr: "temple bouddhiste", img: "🛕" },
      { jp: "神社", kana: "じんじゃ", romaji: "jinja", fr: "sanctuaire shintō", img: "⛩️" },
      { jp: "海", kana: "うみ", romaji: "umi", fr: "mer (plage)", img: "🏖️" },
      { jp: "山", kana: "やま", romaji: "yama", fr: "montagne (excursion)", img: "⛰️" },
      { jp: "川", kana: "かわ", romaji: "kawa", fr: "rivière (site)", img: "🏞️" },
      { jp: "湖", kana: "みずうみ", romaji: "mizuumi", fr: "lac", img: "🌊" },
      { jp: "世界", kana: "せかい", romaji: "sekai", fr: "monde", img: "🌎" },
      { jp: "国", kana: "くに", romaji: "kuni", fr: "pays", img: "🏳️" },
      { jp: "都市", kana: "とし", romaji: "toshi", fr: "grande ville", img: "🌆" },
      { jp: "田舎", kana: "いなか", romaji: "inaka", fr: "campagne", img: "🌾" },
      { jp: "通訳", kana: "つうやく", romaji: "tsūyaku", fr: "interprète", img: "🗣️" },
      { jp: "両替", kana: "りょうがえ", romaji: "ryōgae", fr: "change (devises)", img: "💱" },
      { jp: "チケット", kana: "チケット", romaji: "chiketto", fr: "billet (entrée)", img: "🎟️" },
      { jp: "出口", kana: "でぐち", romaji: "deguchi", fr: "sortie", img: "🚪" },
      { jp: "入口", kana: "いりぐち", romaji: "iriguchi", fr: "entrée", img: "🚪" },
      { jp: "案内図", kana: "あんないず", romaji: "annaizu", fr: "plan (panneau)", img: "🗺️" },
      { jp: "記念品", kana: "きねんひん", romaji: "kinenhin", fr: "souvenir (objet)", img: "🎁" },
      { jp: "冒険", kana: "ぼうけん", romaji: "bōken", fr: "aventure", img: "🧗" },
      { jp: "休暇", kana: "きゅうか", romaji: "kyūka", fr: "vacances", img: "🏖️" },
    ],
  },
  {
    theme: "En ville & lieux",
    icon: "🏙️",
    mots: [
      { jp: "町", kana: "まち", romaji: "machi", fr: "ville / quartier", img: "🏙️" },
      { jp: "都会", kana: "とかい", romaji: "tokai", fr: "grande ville (métropole)", img: "🌆" },
      { jp: "建物", kana: "たてもの", romaji: "tatemono", fr: "bâtiment", img: "🏢" },
      { jp: "ビル", kana: "ビル", romaji: "biru", fr: "immeuble", img: "🏢" },
      { jp: "家", kana: "いえ", romaji: "ie", fr: "maison (habitation)", img: "🏠" },
      { jp: "銀行", kana: "ぎんこう", romaji: "ginkō", fr: "banque (lieu)", img: "🏦" },
      { jp: "病院", kana: "びょういん", romaji: "byōin", fr: "hôpital", img: "🏥" },
      { jp: "薬局", kana: "やっきょく", romaji: "yakkyoku", fr: "pharmacie", img: "💊" },
      { jp: "郵便局", kana: "ゆうびんきょく", romaji: "yūbinkyoku", fr: "bureau de poste", img: "🏤" },
      { jp: "学校", kana: "がっこう", romaji: "gakkō", fr: "école (bâtiment)", img: "🏫" },
      { jp: "図書館", kana: "としょかん", romaji: "toshokan", fr: "bibliothèque", img: "📚" },
      { jp: "公園", kana: "こうえん", romaji: "kōen", fr: "parc", img: "🏞️" },
      { jp: "交番", kana: "こうばん", romaji: "kōban", fr: "poste de police", img: "🚓" },
      { jp: "警察署", kana: "けいさつしょ", romaji: "keisatsusho", fr: "commissariat", img: "🚔" },
      { jp: "消防署", kana: "しょうぼうしょ", romaji: "shōbōsho", fr: "caserne de pompiers", img: "🚒" },
      { jp: "市役所", kana: "しやくしょ", romaji: "shiyakusho", fr: "mairie", img: "🏛️" },
      { jp: "駅", kana: "えき", romaji: "eki", fr: "gare (en ville)", img: "🚉" },
      { jp: "映画館", kana: "えいがかん", romaji: "eigakan", fr: "cinéma", img: "🎬" },
      { jp: "美術館", kana: "びじゅつかん", romaji: "bijutsukan", fr: "musée d'art", img: "🖼️" },
      { jp: "博物館", kana: "はくぶつかん", romaji: "hakubutsukan", fr: "musée", img: "🏛️" },
      { jp: "動物園", kana: "どうぶつえん", romaji: "dōbutsuen", fr: "zoo", img: "🦁" },
      { jp: "水族館", kana: "すいぞくかん", romaji: "suizokukan", fr: "aquarium", img: "🐠" },
      { jp: "遊園地", kana: "ゆうえんち", romaji: "yūenchi", fr: "parc d'attractions", img: "🎢" },
      { jp: "神社", kana: "じんじゃ", romaji: "jinja", fr: "sanctuaire (en ville)", img: "⛩️" },
      { jp: "寺", kana: "てら", romaji: "tera", fr: "temple (en ville)", img: "🛕" },
      { jp: "教会", kana: "きょうかい", romaji: "kyōkai", fr: "église", img: "⛪" },
      { jp: "コンビニ", kana: "コンビニ", romaji: "konbini", fr: "supérette (du coin)", img: "🏪" },
      { jp: "スーパー", kana: "スーパー", romaji: "sūpā", fr: "supermarché (du quartier)", img: "🛒" },
      { jp: "レストラン", kana: "レストラン", romaji: "resutoran", fr: "restaurant (lieu)", img: "🍽️" },
      { jp: "カフェ", kana: "カフェ", romaji: "kafe", fr: "café (lieu)", img: "🍰" },
      { jp: "ホテル", kana: "ホテル", romaji: "hoteru", fr: "hôtel (en ville)", img: "🏨" },
      { jp: "空港", kana: "くうこう", romaji: "kūkō", fr: "aéroport (lieu)", img: "🛫" },
      { jp: "駐車場", kana: "ちゅうしゃじょう", romaji: "chūshajō", fr: "parking (lieu)", img: "🅿️" },
      { jp: "橋", kana: "はし", romaji: "hashi", fr: "pont", img: "🌉" },
      { jp: "川", kana: "かわ", romaji: "kawa", fr: "rivière (en ville)", img: "🏞️" },
      { jp: "道", kana: "みち", romaji: "michi", fr: "rue / chemin (ville)", img: "🛣️" },
      { jp: "通り", kana: "とおり", romaji: "tōri", fr: "avenue", img: "🛤️" },
      { jp: "角", kana: "かど", romaji: "kado", fr: "coin (de rue)", img: "📐" },
      { jp: "広場", kana: "ひろば", romaji: "hiroba", fr: "place (esplanade)", img: "⛲" },
      { jp: "噴水", kana: "ふんすい", romaji: "funsui", fr: "fontaine", img: "⛲" },
      { jp: "信号", kana: "しんごう", romaji: "shingō", fr: "feu tricolore (ville)", img: "🚦" },
      { jp: "交差点", kana: "こうさてん", romaji: "kōsaten", fr: "carrefour (ville)", img: "➕" },
      { jp: "歩道", kana: "ほどう", romaji: "hodō", fr: "trottoir", img: "🚶" },
      { jp: "ビル街", kana: "ビルがい", romaji: "birugai", fr: "quartier d'affaires", img: "🏙️" },
      { jp: "住宅街", kana: "じゅうたくがい", romaji: "jūtakugai", fr: "quartier résidentiel", img: "🏘️" },
      { jp: "工場", kana: "こうじょう", romaji: "kōjō", fr: "usine", img: "🏭" },
      { jp: "農場", kana: "のうじょう", romaji: "nōjō", fr: "ferme", img: "🚜" },
      { jp: "港", kana: "みなと", romaji: "minato", fr: "port (lieu)", img: "⚓" },
      { jp: "タワー", kana: "タワー", romaji: "tawā", fr: "tour", img: "🗼" },
      { jp: "スタジアム", kana: "スタジアム", romaji: "sutajiamu", fr: "stade", img: "🏟️" },
    ],
  },
  {
    theme: "La maison",
    icon: "🏠",
    mots: [
      { jp: "家", kana: "いえ", romaji: "ie", fr: "maison", img: "🏠" },
      { jp: "うち", kana: "うち", romaji: "uchi", fr: "chez soi", img: "🏡" },
      { jp: "マンション", kana: "マンション", romaji: "manshon", fr: "appartement (immeuble)", img: "🏢" },
      { jp: "アパート", kana: "アパート", romaji: "apāto", fr: "appartement", img: "🏬" },
      { jp: "部屋", kana: "へや", romaji: "heya", fr: "pièce / chambre", img: "🚪" },
      { jp: "玄関", kana: "げんかん", romaji: "genkan", fr: "entrée (vestibule)", img: "🚪" },
      { jp: "台所", kana: "だいどころ", romaji: "daidokoro", fr: "cuisine (pièce)", img: "🍳" },
      { jp: "キッチン", kana: "キッチン", romaji: "kitchin", fr: "cuisine (moderne)", img: "🍽️" },
      { jp: "居間", kana: "いま", romaji: "ima", fr: "salon", img: "🛋️" },
      { jp: "リビング", kana: "リビング", romaji: "ribingu", fr: "séjour", img: "🛋️" },
      { jp: "寝室", kana: "しんしつ", romaji: "shinshitsu", fr: "chambre à coucher", img: "🛏️" },
      { jp: "お風呂", kana: "おふろ", romaji: "ofuro", fr: "bain", img: "🛁" },
      { jp: "浴室", kana: "よくしつ", romaji: "yokushitsu", fr: "salle de bain", img: "🛁" },
      { jp: "トイレ", kana: "トイレ", romaji: "toire", fr: "toilettes", img: "🚽" },
      { jp: "洗面所", kana: "せんめんじょ", romaji: "senmenjo", fr: "coin lavabo", img: "🚰" },
      { jp: "廊下", kana: "ろうか", romaji: "rōka", fr: "couloir", img: "🚪" },
      { jp: "階段", kana: "かいだん", romaji: "kaidan", fr: "escalier", img: "🪜" },
      { jp: "屋根", kana: "やね", romaji: "yane", fr: "toit", img: "🏠" },
      { jp: "壁", kana: "かべ", romaji: "kabe", fr: "mur", img: "🧱" },
      { jp: "床", kana: "ゆか", romaji: "yuka", fr: "sol / plancher", img: "🧹" },
      { jp: "天井", kana: "てんじょう", romaji: "tenjō", fr: "plafond", img: "⬆️" },
      { jp: "窓", kana: "まど", romaji: "mado", fr: "fenêtre", img: "🪟" },
      { jp: "ドア", kana: "ドア", romaji: "doa", fr: "porte", img: "🚪" },
      { jp: "庭", kana: "にわ", romaji: "niwa", fr: "jardin", img: "🌳" },
      { jp: "ベランダ", kana: "ベランダ", romaji: "beranda", fr: "balcon", img: "🪴" },
      { jp: "家具", kana: "かぐ", romaji: "kagu", fr: "meubles", img: "🪑" },
      { jp: "机", kana: "つくえ", romaji: "tsukue", fr: "bureau (meuble)", img: "🪑" },
      { jp: "椅子", kana: "いす", romaji: "isu", fr: "chaise", img: "💺" },
      { jp: "テーブル", kana: "テーブル", romaji: "tēburu", fr: "table", img: "🪑" },
      { jp: "ベッド", kana: "ベッド", romaji: "beddo", fr: "lit", img: "🛏️" },
      { jp: "ソファ", kana: "ソファ", romaji: "sofa", fr: "canapé", img: "🛋️" },
      { jp: "本棚", kana: "ほんだな", romaji: "hondana", fr: "étagère à livres", img: "📚" },
      { jp: "引き出し", kana: "ひきだし", romaji: "hikidashi", fr: "tiroir", img: "🗄️" },
      { jp: "押し入れ", kana: "おしいれ", romaji: "oshiire", fr: "placard (futon)", img: "🚪" },
      { jp: "冷蔵庫", kana: "れいぞうこ", romaji: "reizōko", fr: "réfrigérateur", img: "🧊" },
      { jp: "電子レンジ", kana: "でんしレンジ", romaji: "denshi renji", fr: "four micro-ondes", img: "📟" },
      { jp: "電気", kana: "でんき", romaji: "denki", fr: "électricité / lumière", img: "💡" },
      { jp: "電灯", kana: "でんとう", romaji: "dentō", fr: "lampe", img: "💡" },
      { jp: "テレビ", kana: "テレビ", romaji: "terebi", fr: "télévision", img: "📺" },
      { jp: "エアコン", kana: "エアコン", romaji: "eakon", fr: "climatiseur", img: "❄️" },
      { jp: "洗濯機", kana: "せんたくき", romaji: "sentakuki", fr: "machine à laver", img: "🧺" },
      { jp: "掃除機", kana: "そうじき", romaji: "sōjiki", fr: "aspirateur", img: "🧹" },
      { jp: "鏡", kana: "かがみ", romaji: "kagami", fr: "miroir", img: "🪞" },
      { jp: "時計", kana: "とけい", romaji: "tokei", fr: "horloge", img: "🕐" },
      { jp: "布団", kana: "ふとん", romaji: "futon", fr: "futon", img: "🛏️" },
      { jp: "枕", kana: "まくら", romaji: "makura", fr: "oreiller", img: "🛏️" },
      { jp: "毛布", kana: "もうふ", romaji: "mōfu", fr: "couverture", img: "🛌" },
      { jp: "タオル", kana: "タオル", romaji: "taoru", fr: "serviette (de bain)", img: "🧻" },
      { jp: "鍵", kana: "かぎ", romaji: "kagi", fr: "clé", img: "🔑" },
      { jp: "ゴミ箱", kana: "ゴミばこ", romaji: "gomibako", fr: "poubelle", img: "🗑️" },
    ],
  },
  {
    theme: "Vêtements",
    icon: "👕",
    mots: [
      { jp: "服", kana: "ふく", romaji: "fuku", fr: "vêtements", img: "👕" },
      { jp: "洋服", kana: "ようふく", romaji: "yōfuku", fr: "vêtements (occidentaux)", img: "👗" },
      { jp: "着物", kana: "きもの", romaji: "kimono", fr: "kimono", img: "👘" },
      { jp: "浴衣", kana: "ゆかた", romaji: "yukata", fr: "yukata", img: "👘" },
      { jp: "シャツ", kana: "シャツ", romaji: "shatsu", fr: "chemise", img: "👔" },
      { jp: "Tシャツ", kana: "ティーシャツ", romaji: "tīshatsu", fr: "tee-shirt", img: "👕" },
      { jp: "ワイシャツ", kana: "ワイシャツ", romaji: "waishatsu", fr: "chemise habillée", img: "👔" },
      { jp: "ブラウス", kana: "ブラウス", romaji: "burausu", fr: "chemisier", img: "👚" },
      { jp: "セーター", kana: "セーター", romaji: "sētā", fr: "pull", img: "🧶" },
      { jp: "ジャケット", kana: "ジャケット", romaji: "jaketto", fr: "veste", img: "🧥" },
      { jp: "コート", kana: "コート", romaji: "kōto", fr: "manteau", img: "🧥" },
      { jp: "ズボン", kana: "ズボン", romaji: "zubon", fr: "pantalon", img: "👖" },
      { jp: "ジーンズ", kana: "ジーンズ", romaji: "jīnzu", fr: "jean", img: "👖" },
      { jp: "スカート", kana: "スカート", romaji: "sukāto", fr: "jupe", img: "👗" },
      { jp: "ワンピース", kana: "ワンピース", romaji: "wanpīsu", fr: "robe", img: "👗" },
      { jp: "ドレス", kana: "ドレス", romaji: "doresu", fr: "robe (de soirée)", img: "👰" },
      { jp: "スーツ", kana: "スーツ", romaji: "sūtsu", fr: "costume", img: "🕴️" },
      { jp: "下着", kana: "したぎ", romaji: "shitagi", fr: "sous-vêtements", img: "🩲" },
      { jp: "靴下", kana: "くつした", romaji: "kutsushita", fr: "chaussettes", img: "🧦" },
      { jp: "靴", kana: "くつ", romaji: "kutsu", fr: "chaussures", img: "👟" },
      { jp: "運動靴", kana: "うんどうぐつ", romaji: "undōgutsu", fr: "baskets", img: "👟" },
      { jp: "革靴", kana: "かわぐつ", romaji: "kawagutsu", fr: "chaussures en cuir", img: "👞" },
      { jp: "ブーツ", kana: "ブーツ", romaji: "būtsu", fr: "bottes", img: "🥾" },
      { jp: "サンダル", kana: "サンダル", romaji: "sandaru", fr: "sandales", img: "🩴" },
      { jp: "スリッパ", kana: "スリッパ", romaji: "surippa", fr: "chaussons", img: "🥿" },
      { jp: "帽子", kana: "ぼうし", romaji: "bōshi", fr: "chapeau", img: "🧢" },
      { jp: "キャップ", kana: "キャップ", romaji: "kyappu", fr: "casquette", img: "🧢" },
      { jp: "手袋", kana: "てぶくろ", romaji: "tebukuro", fr: "gants", img: "🧤" },
      { jp: "マフラー", kana: "マフラー", romaji: "mafurā", fr: "écharpe", img: "🧣" },
      { jp: "ネクタイ", kana: "ネクタイ", romaji: "nekutai", fr: "cravate", img: "👔" },
      { jp: "ベルト", kana: "ベルト", romaji: "beruto", fr: "ceinture", img: "🩹" },
      { jp: "眼鏡", kana: "めがね", romaji: "megane", fr: "lunettes", img: "👓" },
      { jp: "サングラス", kana: "サングラス", romaji: "sangurasu", fr: "lunettes de soleil", img: "🕶️" },
      { jp: "時計", kana: "とけい", romaji: "tokei", fr: "montre", img: "⌚" },
      { jp: "指輪", kana: "ゆびわ", romaji: "yubiwa", fr: "bague", img: "💍" },
      { jp: "ネックレス", kana: "ネックレス", romaji: "nekkuresu", fr: "collier", img: "📿" },
      { jp: "イヤリング", kana: "イヤリング", romaji: "iyaringu", fr: "boucles d'oreilles", img: "💎" },
      { jp: "ピアス", kana: "ピアス", romaji: "piasu", fr: "boucles (percées)", img: "💠" },
      { jp: "ブレスレット", kana: "ブレスレット", romaji: "buresuretto", fr: "bracelet", img: "📿" },
      { jp: "かばん", kana: "かばん", romaji: "kaban", fr: "sac (cartable)", img: "👜" },
      { jp: "ハンドバッグ", kana: "ハンドバッグ", romaji: "handobaggu", fr: "sac à main", img: "👜" },
      { jp: "リュック", kana: "リュック", romaji: "ryukku", fr: "sac à dos (mode)", img: "🎒" },
      { jp: "財布", kana: "さいふ", romaji: "saifu", fr: "portefeuille (accessoire)", img: "👛" },
      { jp: "傘", kana: "かさ", romaji: "kasa", fr: "parapluie", img: "☂️" },
      { jp: "マスク", kana: "マスク", romaji: "masuku", fr: "masque", img: "😷" },
      { jp: "パジャマ", kana: "パジャマ", romaji: "pajama", fr: "pyjama", img: "🛌" },
      { jp: "水着", kana: "みずぎ", romaji: "mizugi", fr: "maillot de bain", img: "🩱" },
      { jp: "制服", kana: "せいふく", romaji: "seifuku", fr: "uniforme", img: "🎽" },
      { jp: "ポケット", kana: "ポケット", romaji: "poketto", fr: "poche", img: "👖" },
      { jp: "ボタン", kana: "ボタン", romaji: "botan", fr: "bouton", img: "🔘" },
    ],
  },
  {
    theme: "École & études",
    icon: "🏫",
    mots: [
      { jp: "学校", kana: "がっこう", romaji: "gakkō", fr: "école", img: "🏫" },
      { jp: "小学校", kana: "しょうがっこう", romaji: "shōgakkō", fr: "école primaire", img: "🎒" },
      { jp: "中学校", kana: "ちゅうがっこう", romaji: "chūgakkō", fr: "collège", img: "🏫" },
      { jp: "高校", kana: "こうこう", romaji: "kōkō", fr: "lycée", img: "🏫" },
      { jp: "大学", kana: "だいがく", romaji: "daigaku", fr: "université", img: "🎓" },
      { jp: "幼稚園", kana: "ようちえん", romaji: "yōchien", fr: "école maternelle", img: "🧸" },
      { jp: "教室", kana: "きょうしつ", romaji: "kyōshitsu", fr: "salle de classe", img: "🪑" },
      { jp: "学生", kana: "がくせい", romaji: "gakusei", fr: "étudiant(e)", img: "🧑‍🎓" },
      { jp: "生徒", kana: "せいと", romaji: "seito", fr: "élève", img: "🧑‍🏫" },
      { jp: "先生", kana: "せんせい", romaji: "sensei", fr: "professeur", img: "👨‍🏫" },
      { jp: "校長", kana: "こうちょう", romaji: "kōchō", fr: "directeur (école)", img: "🧑‍💼" },
      { jp: "クラス", kana: "クラス", romaji: "kurasu", fr: "classe (groupe)", img: "👥" },
      { jp: "授業", kana: "じゅぎょう", romaji: "jugyō", fr: "cours (leçon)", img: "📖" },
      { jp: "勉強", kana: "べんきょう", romaji: "benkyō", fr: "étude", img: "📚" },
      { jp: "宿題", kana: "しゅくだい", romaji: "shukudai", fr: "devoirs", img: "📝" },
      { jp: "試験", kana: "しけん", romaji: "shiken", fr: "examen", img: "🧑‍💻" },
      { jp: "テスト", kana: "テスト", romaji: "tesuto", fr: "contrôle", img: "📝" },
      { jp: "成績", kana: "せいせき", romaji: "seiseki", fr: "notes / résultats", img: "📊" },
      { jp: "質問", kana: "しつもん", romaji: "shitsumon", fr: "question", img: "❓" },
      { jp: "答え", kana: "こたえ", romaji: "kotae", fr: "réponse", img: "✅" },
      { jp: "問題", kana: "もんだい", romaji: "mondai", fr: "problème / exercice", img: "❔" },
      { jp: "教科書", kana: "きょうかしょ", romaji: "kyōkasho", fr: "manuel scolaire", img: "📘" },
      { jp: "本", kana: "ほん", romaji: "hon", fr: "livre", img: "📖" },
      { jp: "ノート", kana: "ノート", romaji: "nōto", fr: "cahier", img: "📓" },
      { jp: "鉛筆", kana: "えんぴつ", romaji: "enpitsu", fr: "crayon", img: "✏️" },
      { jp: "ペン", kana: "ペン", romaji: "pen", fr: "stylo", img: "🖊️" },
      { jp: "消しゴム", kana: "けしゴム", romaji: "keshigomu", fr: "gomme", img: "🧽" },
      { jp: "定規", kana: "じょうぎ", romaji: "jōgi", fr: "règle", img: "📏" },
      { jp: "はさみ", kana: "はさみ", romaji: "hasami", fr: "ciseaux", img: "✂️" },
      { jp: "のり", kana: "のり", romaji: "nori", fr: "colle", img: "🧴" },
      { jp: "筆箱", kana: "ふでばこ", romaji: "fudebako", fr: "trousse", img: "🖊️" },
      { jp: "ランドセル", kana: "ランドセル", romaji: "randoseru", fr: "cartable", img: "🎒" },
      { jp: "黒板", kana: "こくばん", romaji: "kokuban", fr: "tableau noir", img: "📋" },
      { jp: "チョーク", kana: "チョーク", romaji: "chōku", fr: "craie", img: "🖍️" },
      { jp: "机", kana: "つくえ", romaji: "tsukue", fr: "bureau (pupitre)", img: "🪑" },
      { jp: "図書館", kana: "としょかん", romaji: "toshokan", fr: "bibliothèque (études)", img: "📚" },
      { jp: "辞書", kana: "じしょ", romaji: "jisho", fr: "dictionnaire", img: "📕" },
      { jp: "漢字", kana: "かんじ", romaji: "kanji", fr: "kanji (idéogramme)", img: "🈶" },
      { jp: "平仮名", kana: "ひらがな", romaji: "hiragana", fr: "hiragana", img: "🅰️" },
      { jp: "片仮名", kana: "かたかな", romaji: "katakana", fr: "katakana", img: "🅱️" },
      { jp: "言葉", kana: "ことば", romaji: "kotoba", fr: "mot / langue", img: "💬" },
      { jp: "文法", kana: "ぶんぽう", romaji: "bunpō", fr: "grammaire", img: "📐" },
      { jp: "単語", kana: "たんご", romaji: "tango", fr: "vocabulaire", img: "🔤" },
      { jp: "発音", kana: "はつおん", romaji: "hatsuon", fr: "prononciation", img: "🗣️" },
      { jp: "作文", kana: "さくぶん", romaji: "sakubun", fr: "rédaction", img: "📝" },
      { jp: "読書", kana: "どくしょ", romaji: "dokusho", fr: "lecture", img: "📖" },
      { jp: "数学", kana: "すうがく", romaji: "sūgaku", fr: "mathématiques", img: "➗" },
      { jp: "科学", kana: "かがく", romaji: "kagaku", fr: "science", img: "🔬" },
      { jp: "歴史", kana: "れきし", romaji: "rekishi", fr: "histoire", img: "📜" },
      { jp: "卒業", kana: "そつぎょう", romaji: "sotsugyō", fr: "remise de diplôme", img: "🎓" },
    ],
  },
  {
    theme: "Métiers & travail",
    icon: "💼",
    mots: [
      { jp: "仕事", kana: "しごと", romaji: "shigoto", fr: "travail", img: "💼" },
      { jp: "職業", kana: "しょくぎょう", romaji: "shokugyō", fr: "profession", img: "🧑‍💼" },
      { jp: "会社", kana: "かいしゃ", romaji: "kaisha", fr: "entreprise", img: "🏢" },
      { jp: "会社員", kana: "かいしゃいん", romaji: "kaishain", fr: "employé(e)", img: "🧑‍💼" },
      { jp: "サラリーマン", kana: "サラリーマン", romaji: "sararīman", fr: "salarié (col blanc)", img: "🕴️" },
      { jp: "社長", kana: "しゃちょう", romaji: "shachō", fr: "PDG", img: "👔" },
      { jp: "部長", kana: "ぶちょう", romaji: "buchō", fr: "chef de service", img: "🧑‍💼" },
      { jp: "医者", kana: "いしゃ", romaji: "isha", fr: "médecin", img: "👨‍⚕️" },
      { jp: "歯医者", kana: "はいしゃ", romaji: "haisha", fr: "dentiste", img: "🦷" },
      { jp: "看護師", kana: "かんごし", romaji: "kangoshi", fr: "infirmier / infirmière", img: "👩‍⚕️" },
      { jp: "薬剤師", kana: "やくざいし", romaji: "yakuzaishi", fr: "pharmacien", img: "💊" },
      { jp: "先生", kana: "せんせい", romaji: "sensei", fr: "professeur / maître", img: "👨‍🏫" },
      { jp: "教師", kana: "きょうし", romaji: "kyōshi", fr: "enseignant(e)", img: "🧑‍🏫" },
      { jp: "学者", kana: "がくしゃ", romaji: "gakusha", fr: "chercheur / savant", img: "🔬" },
      { jp: "弁護士", kana: "べんごし", romaji: "bengoshi", fr: "avocat", img: "⚖️" },
      { jp: "警察官", kana: "けいさつかん", romaji: "keisatsukan", fr: "policier", img: "👮" },
      { jp: "消防士", kana: "しょうぼうし", romaji: "shōbōshi", fr: "pompier", img: "🧑‍🚒" },
      { jp: "軍人", kana: "ぐんじん", romaji: "gunjin", fr: "militaire", img: "🪖" },
      { jp: "店員", kana: "てんいん", romaji: "ten'in", fr: "vendeur / vendeuse", img: "🛍️" },
      { jp: "料理人", kana: "りょうりにん", romaji: "ryōrinin", fr: "cuisinier", img: "👨‍🍳" },
      { jp: "コック", kana: "コック", romaji: "kokku", fr: "cuisinier (cook)", img: "👨‍🍳" },
      { jp: "パン屋", kana: "パンや", romaji: "pan'ya", fr: "boulanger", img: "🥖" },
      { jp: "農家", kana: "のうか", romaji: "nōka", fr: "agriculteur", img: "🧑‍🌾" },
      { jp: "漁師", kana: "りょうし", romaji: "ryōshi", fr: "pêcheur", img: "🎣" },
      { jp: "運転手", kana: "うんてんしゅ", romaji: "untenshu", fr: "chauffeur (métier)", img: "🚗" },
      { jp: "パイロット", kana: "パイロット", romaji: "pairotto", fr: "pilote", img: "🧑‍✈️" },
      { jp: "客室乗務員", kana: "きゃくしつじょうむいん", romaji: "kyakushitsu jōmuin", fr: "agent de bord", img: "🛫" },
      { jp: "エンジニア", kana: "エンジニア", romaji: "enjinia", fr: "ingénieur", img: "🧑‍🔧" },
      { jp: "プログラマー", kana: "プログラマー", romaji: "puroguramā", fr: "programmeur", img: "💻" },
      { jp: "デザイナー", kana: "デザイナー", romaji: "dezainā", fr: "designer", img: "🎨" },
      { jp: "画家", kana: "がか", romaji: "gaka", fr: "peintre (artiste)", img: "🖼️" },
      { jp: "歌手", kana: "かしゅ", romaji: "kashu", fr: "chanteur", img: "🎤" },
      { jp: "俳優", kana: "はいゆう", romaji: "haiyū", fr: "acteur", img: "🎭" },
      { jp: "音楽家", kana: "おんがくか", romaji: "ongakuka", fr: "musicien", img: "🎼" },
      { jp: "作家", kana: "さっか", romaji: "sakka", fr: "écrivain", img: "✍️" },
      { jp: "記者", kana: "きしゃ", romaji: "kisha", fr: "journaliste", img: "📰" },
      { jp: "通訳", kana: "つうやく", romaji: "tsūyaku", fr: "interprète (métier)", img: "🗣️" },
      { jp: "銀行員", kana: "ぎんこういん", romaji: "ginkōin", fr: "banquier", img: "🏦" },
      { jp: "公務員", kana: "こうむいん", romaji: "kōmuin", fr: "fonctionnaire", img: "🏛️" },
      { jp: "美容師", kana: "びようし", romaji: "biyōshi", fr: "coiffeur", img: "💇" },
      { jp: "大工", kana: "だいく", romaji: "daiku", fr: "charpentier", img: "🔨" },
      { jp: "電気屋", kana: "でんきや", romaji: "denkiya", fr: "électricien", img: "💡" },
      { jp: "政治家", kana: "せいじか", romaji: "seijika", fr: "politicien", img: "🗳️" },
      { jp: "社員", kana: "しゃいん", romaji: "shain", fr: "membre du personnel", img: "🧑‍💼" },
      { jp: "アルバイト", kana: "アルバイト", romaji: "arubaito", fr: "petit boulot", img: "🧑‍🍳" },
      { jp: "給料", kana: "きゅうりょう", romaji: "kyūryō", fr: "salaire", img: "💴" },
      { jp: "会議", kana: "かいぎ", romaji: "kaigi", fr: "réunion", img: "🧑‍🤝‍🧑" },
      { jp: "出張", kana: "しゅっちょう", romaji: "shutchō", fr: "voyage d'affaires", img: "🧳" },
      { jp: "残業", kana: "ざんぎょう", romaji: "zangyō", fr: "heures supplémentaires", img: "⏰" },
      { jp: "休憩", kana: "きゅうけい", romaji: "kyūkei", fr: "pause", img: "☕" },
    ],
  },
  {
    theme: "Animaux",
    icon: "🐾",
    mots: [
      { jp: "動物", kana: "どうぶつ", romaji: "dōbutsu", fr: "animal", img: "🐾" },
      { jp: "犬", kana: "いぬ", romaji: "inu", fr: "chien", img: "🐶" },
      { jp: "猫", kana: "ねこ", romaji: "neko", fr: "chat", img: "🐱" },
      { jp: "鳥", kana: "とり", romaji: "tori", fr: "oiseau", img: "🐦" },
      { jp: "魚", kana: "さかな", romaji: "sakana", fr: "poisson (animal)", img: "🐟" },
      { jp: "馬", kana: "うま", romaji: "uma", fr: "cheval", img: "🐴" },
      { jp: "牛", kana: "うし", romaji: "ushi", fr: "vache", img: "🐮" },
      { jp: "豚", kana: "ぶた", romaji: "buta", fr: "cochon", img: "🐷" },
      { jp: "羊", kana: "ひつじ", romaji: "hitsuji", fr: "mouton", img: "🐑" },
      { jp: "山羊", kana: "やぎ", romaji: "yagi", fr: "chèvre", img: "🐐" },
      { jp: "鶏", kana: "にわとり", romaji: "niwatori", fr: "poule", img: "🐔" },
      { jp: "兎", kana: "うさぎ", romaji: "usagi", fr: "lapin", img: "🐰" },
      { jp: "鼠", kana: "ねずみ", romaji: "nezumi", fr: "souris", img: "🐭" },
      { jp: "熊", kana: "くま", romaji: "kuma", fr: "ours", img: "🐻" },
      { jp: "象", kana: "ぞう", romaji: "zō", fr: "éléphant", img: "🐘" },
      { jp: "虎", kana: "とら", romaji: "tora", fr: "tigre", img: "🐯" },
      { jp: "獅子", kana: "しし", romaji: "shishi", fr: "lion", img: "🦁" },
      { jp: "猿", kana: "さる", romaji: "saru", fr: "singe", img: "🐵" },
      { jp: "狐", kana: "きつね", romaji: "kitsune", fr: "renard", img: "🦊" },
      { jp: "狼", kana: "おおかみ", romaji: "ōkami", fr: "loup", img: "🐺" },
      { jp: "鹿", kana: "しか", romaji: "shika", fr: "cerf", img: "🦌" },
      { jp: "きりん", kana: "きりん", romaji: "kirin", fr: "girafe", img: "🦒" },
      { jp: "河馬", kana: "かば", romaji: "kaba", fr: "hippopotame", img: "🦛" },
      { jp: "パンダ", kana: "パンダ", romaji: "panda", fr: "panda", img: "🐼" },
      { jp: "コアラ", kana: "コアラ", romaji: "koara", fr: "koala", img: "🐨" },
      { jp: "カンガルー", kana: "カンガルー", romaji: "kangarū", fr: "kangourou", img: "🦘" },
      { jp: "亀", kana: "かめ", romaji: "kame", fr: "tortue", img: "🐢" },
      { jp: "蛇", kana: "へび", romaji: "hebi", fr: "serpent", img: "🐍" },
      { jp: "蛙", kana: "かえる", romaji: "kaeru", fr: "grenouille", img: "🐸" },
      { jp: "蜥蜴", kana: "とかげ", romaji: "tokage", fr: "lézard", img: "🦎" },
      { jp: "鰐", kana: "わに", romaji: "wani", fr: "crocodile", img: "🐊" },
      { jp: "鯨", kana: "くじら", romaji: "kujira", fr: "baleine", img: "🐋" },
      { jp: "海豚", kana: "いるか", romaji: "iruka", fr: "dauphin", img: "🐬" },
      { jp: "鮫", kana: "さめ", romaji: "same", fr: "requin", img: "🦈" },
      { jp: "蛸", kana: "たこ", romaji: "tako", fr: "poulpe", img: "🐙" },
      { jp: "烏賊", kana: "いか", romaji: "ika", fr: "calamar", img: "🦑" },
      { jp: "蟹", kana: "かに", romaji: "kani", fr: "crabe", img: "🦀" },
      { jp: "海老", kana: "えび", romaji: "ebi", fr: "crevette", img: "🦐" },
      { jp: "貝", kana: "かい", romaji: "kai", fr: "coquillage", img: "🐚" },
      { jp: "虫", kana: "むし", romaji: "mushi", fr: "insecte", img: "🐛" },
      { jp: "蝶", kana: "ちょう", romaji: "chō", fr: "papillon", img: "🦋" },
      { jp: "蜂", kana: "はち", romaji: "hachi", fr: "abeille", img: "🐝" },
      { jp: "蟻", kana: "あり", romaji: "ari", fr: "fourmi", img: "🐜" },
      { jp: "蜘蛛", kana: "くも", romaji: "kumo", fr: "araignée", img: "🕷️" },
      { jp: "蚊", kana: "か", romaji: "ka", fr: "moustique", img: "🦟" },
      { jp: "鴨", kana: "かも", romaji: "kamo", fr: "canard", img: "🦆" },
      { jp: "鷲", kana: "わし", romaji: "washi", fr: "aigle", img: "🦅" },
      { jp: "梟", kana: "ふくろう", romaji: "fukurō", fr: "hibou", img: "🦉" },
      { jp: "孔雀", kana: "くじゃく", romaji: "kujaku", fr: "paon", img: "🦚" },
      { jp: "恐竜", kana: "きょうりゅう", romaji: "kyōryū", fr: "dinosaure", img: "🦖" },
    ],
  },
  {
    theme: "Nature & météo",
    icon: "🌤️",
    mots: [
      { jp: "自然", kana: "しぜん", romaji: "shizen", fr: "nature", img: "🌿" },
      { jp: "天気", kana: "てんき", romaji: "tenki", fr: "temps (météo)", img: "🌤️" },
      { jp: "空", kana: "そら", romaji: "sora", fr: "ciel", img: "🌌" },
      { jp: "太陽", kana: "たいよう", romaji: "taiyō", fr: "soleil (astre)", img: "☀️" },
      { jp: "日", kana: "ひ", romaji: "hi", fr: "soleil / jour", img: "🌞" },
      { jp: "月", kana: "つき", romaji: "tsuki", fr: "lune", img: "🌙" },
      { jp: "星", kana: "ほし", romaji: "hoshi", fr: "étoile", img: "⭐" },
      { jp: "雲", kana: "くも", romaji: "kumo", fr: "nuage", img: "☁️" },
      { jp: "雨", kana: "あめ", romaji: "ame", fr: "pluie", img: "🌧️" },
      { jp: "雪", kana: "ゆき", romaji: "yuki", fr: "neige", img: "❄️" },
      { jp: "風", kana: "かぜ", romaji: "kaze", fr: "vent", img: "💨" },
      { jp: "雷", kana: "かみなり", romaji: "kaminari", fr: "tonnerre / foudre", img: "⚡" },
      { jp: "台風", kana: "たいふう", romaji: "taifū", fr: "typhon", img: "🌀" },
      { jp: "虹", kana: "にじ", romaji: "niji", fr: "arc-en-ciel", img: "🌈" },
      { jp: "霧", kana: "きり", romaji: "kiri", fr: "brouillard", img: "🌫️" },
      { jp: "氷", kana: "こおり", romaji: "kōri", fr: "glace", img: "🧊" },
      { jp: "晴れ", kana: "はれ", romaji: "hare", fr: "temps clair", img: "☀️" },
      { jp: "曇り", kana: "くもり", romaji: "kumori", fr: "temps nuageux", img: "☁️" },
      { jp: "嵐", kana: "あらし", romaji: "arashi", fr: "tempête", img: "🌩️" },
      { jp: "暑さ", kana: "あつさ", romaji: "atsusa", fr: "la chaleur", img: "🥵" },
      { jp: "寒さ", kana: "さむさ", romaji: "samusa", fr: "le froid", img: "🥶" },
      { jp: "気温", kana: "きおん", romaji: "kion", fr: "température", img: "🌡️" },
      { jp: "湿度", kana: "しつど", romaji: "shitsudo", fr: "humidité", img: "💧" },
      { jp: "海", kana: "うみ", romaji: "umi", fr: "mer", img: "🌊" },
      { jp: "川", kana: "かわ", romaji: "kawa", fr: "rivière", img: "🏞️" },
      { jp: "湖", kana: "みずうみ", romaji: "mizuumi", fr: "lac (nature)", img: "🏞️" },
      { jp: "池", kana: "いけ", romaji: "ike", fr: "étang", img: "🦆" },
      { jp: "滝", kana: "たき", romaji: "taki", fr: "cascade", img: "🏞️" },
      { jp: "山", kana: "やま", romaji: "yama", fr: "montagne", img: "⛰️" },
      { jp: "丘", kana: "おか", romaji: "oka", fr: "colline", img: "🏞️" },
      { jp: "谷", kana: "たに", romaji: "tani", fr: "vallée", img: "🏞️" },
      { jp: "森", kana: "もり", romaji: "mori", fr: "forêt", img: "🌲" },
      { jp: "林", kana: "はやし", romaji: "hayashi", fr: "bois", img: "🌳" },
      { jp: "木", kana: "き", romaji: "ki", fr: "arbre", img: "🌳" },
      { jp: "葉", kana: "は", romaji: "ha", fr: "feuille", img: "🍃" },
      { jp: "花", kana: "はな", romaji: "hana", fr: "fleur", img: "🌸" },
      { jp: "草", kana: "くさ", romaji: "kusa", fr: "herbe", img: "🌱" },
      { jp: "石", kana: "いし", romaji: "ishi", fr: "pierre", img: "🪨" },
      { jp: "岩", kana: "いわ", romaji: "iwa", fr: "rocher", img: "🪨" },
      { jp: "砂", kana: "すな", romaji: "suna", fr: "sable", img: "🏖️" },
      { jp: "土", kana: "つち", romaji: "tsuchi", fr: "terre (sol)", img: "🟫" },
      { jp: "島", kana: "しま", romaji: "shima", fr: "île", img: "🏝️" },
      { jp: "砂漠", kana: "さばく", romaji: "sabaku", fr: "désert", img: "🏜️" },
      { jp: "火", kana: "ひ", romaji: "hi", fr: "feu", img: "🔥" },
      { jp: "地震", kana: "じしん", romaji: "jishin", fr: "tremblement de terre", img: "🌍" },
      { jp: "洪水", kana: "こうずい", romaji: "kōzui", fr: "inondation", img: "🌊" },
      { jp: "桜", kana: "さくら", romaji: "sakura", fr: "cerisier", img: "🌸" },
      { jp: "紅葉", kana: "こうよう", romaji: "kōyō", fr: "feuilles d'automne", img: "🍁" },
      { jp: "満月", kana: "まんげつ", romaji: "mangetsu", fr: "pleine lune", img: "🌕" },
      { jp: "日の出", kana: "ひので", romaji: "hinode", fr: "lever du soleil", img: "🌅" },
    ],
  },
  {
    theme: "Directions & positions",
    icon: "🧭",
    mots: [
      { jp: "上", kana: "うえ", romaji: "ue", fr: "en haut / dessus", img: "⬆️" },
      { jp: "下", kana: "した", romaji: "shita", fr: "en bas / dessous", img: "⬇️" },
      { jp: "右", kana: "みぎ", romaji: "migi", fr: "droite", img: "➡️" },
      { jp: "左", kana: "ひだり", romaji: "hidari", fr: "gauche", img: "⬅️" },
      { jp: "前", kana: "まえ", romaji: "mae", fr: "devant / avant", img: "⏫" },
      { jp: "後ろ", kana: "うしろ", romaji: "ushiro", fr: "derrière", img: "🔙" },
      { jp: "中", kana: "なか", romaji: "naka", fr: "dedans / milieu", img: "🔲" },
      { jp: "外", kana: "そと", romaji: "soto", fr: "dehors", img: "🌳" },
      { jp: "隣", kana: "となり", romaji: "tonari", fr: "à côté (voisin)", img: "👥" },
      { jp: "近く", kana: "ちかく", romaji: "chikaku", fr: "près", img: "📍" },
      { jp: "遠く", kana: "とおく", romaji: "tōku", fr: "loin", img: "🔭" },
      { jp: "間", kana: "あいだ", romaji: "aida", fr: "entre", img: "↔️" },
      { jp: "向かい", kana: "むかい", romaji: "mukai", fr: "en face", img: "🔛" },
      { jp: "横", kana: "よこ", romaji: "yoko", fr: "sur le côté", img: "↔️" },
      { jp: "そば", kana: "そば", romaji: "soba", fr: "tout près", img: "📍" },
      { jp: "東", kana: "ひがし", romaji: "higashi", fr: "est", img: "🧭" },
      { jp: "西", kana: "にし", romaji: "nishi", fr: "ouest", img: "🧭" },
      { jp: "南", kana: "みなみ", romaji: "minami", fr: "sud", img: "🧭" },
      { jp: "北", kana: "きた", romaji: "kita", fr: "nord", img: "🧭" },
      { jp: "北東", kana: "ほくとう", romaji: "hokutō", fr: "nord-est", img: "🧭" },
      { jp: "北西", kana: "ほくせい", romaji: "hokusei", fr: "nord-ouest", img: "🧭" },
      { jp: "南東", kana: "なんとう", romaji: "nantō", fr: "sud-est", img: "🧭" },
      { jp: "南西", kana: "なんせい", romaji: "nansei", fr: "sud-ouest", img: "🧭" },
      { jp: "真ん中", kana: "まんなか", romaji: "mannaka", fr: "le centre", img: "🎯" },
      { jp: "端", kana: "はし", romaji: "hashi", fr: "le bord", img: "📐" },
      { jp: "角", kana: "かど", romaji: "kado", fr: "le coin (angle)", img: "📐" },
      { jp: "表", kana: "おもて", romaji: "omote", fr: "l'endroit (face)", img: "🔝" },
      { jp: "裏", kana: "うら", romaji: "ura", fr: "l'envers / l'arrière", img: "🔃" },
      { jp: "奥", kana: "おく", romaji: "oku", fr: "le fond", img: "🕳️" },
      { jp: "手前", kana: "てまえ", romaji: "temae", fr: "devant (côté proche)", img: "👉" },
      { jp: "向こう", kana: "むこう", romaji: "mukō", fr: "de l'autre côté", img: "↗️" },
      { jp: "こっち", kana: "こっち", romaji: "kotchi", fr: "par ici", img: "👈" },
      { jp: "そっち", kana: "そっち", romaji: "sotchi", fr: "par là", img: "👉" },
      { jp: "あっち", kana: "あっち", romaji: "atchi", fr: "là-bas (direction)", img: "👆" },
      { jp: "どっち", kana: "どっち", romaji: "dotchi", fr: "lequel / de quel côté", img: "❓" },
      { jp: "ここ", kana: "ここ", romaji: "koko", fr: "ici", img: "📍" },
      { jp: "そこ", kana: "そこ", romaji: "soko", fr: "là", img: "📌" },
      { jp: "あそこ", kana: "あそこ", romaji: "asoko", fr: "là-bas (lieu)", img: "🗺️" },
      { jp: "どこ", kana: "どこ", romaji: "doko", fr: "où", img: "❔" },
      { jp: "右側", kana: "みぎがわ", romaji: "migigawa", fr: "côté droit", img: "➡️" },
      { jp: "左側", kana: "ひだりがわ", romaji: "hidarigawa", fr: "côté gauche", img: "⬅️" },
      { jp: "上の方", kana: "うえのほう", romaji: "ue no hō", fr: "vers le haut", img: "🔼" },
      { jp: "下の方", kana: "したのほう", romaji: "shita no hō", fr: "vers le bas", img: "🔽" },
      { jp: "まっすぐ", kana: "まっすぐ", romaji: "massugu", fr: "tout droit", img: "⬆️" },
      { jp: "曲がる", kana: "まがる", romaji: "magaru", fr: "tourner", img: "🔄" },
      { jp: "方向", kana: "ほうこう", romaji: "hōkō", fr: "direction", img: "🧭" },
      { jp: "位置", kana: "いち", romaji: "ichi", fr: "position", img: "📍" },
      { jp: "場所", kana: "ばしょ", romaji: "basho", fr: "endroit", img: "🗺️" },
      { jp: "距離", kana: "きょり", romaji: "kyori", fr: "distance", img: "📏" },
      { jp: "地図", kana: "ちず", romaji: "chizu", fr: "carte (orientation)", img: "🗺️" },
    ],
  },
  {
    theme: "Adjectifs courants",
    icon: "✨",
    mots: [
      { jp: "大きい", kana: "おおきい", romaji: "ōkii", fr: "grand", img: "🔵" },
      { jp: "小さい", kana: "ちいさい", romaji: "chiisai", fr: "petit", img: "🔹" },
      { jp: "新しい", kana: "あたらしい", romaji: "atarashii", fr: "nouveau", img: "✨" },
      { jp: "古い", kana: "ふるい", romaji: "furui", fr: "vieux / ancien", img: "🏚️" },
      { jp: "良い", kana: "いい", romaji: "ii", fr: "bon / bien", img: "👍" },
      { jp: "悪い", kana: "わるい", romaji: "warui", fr: "mauvais", img: "👎" },
      { jp: "高い", kana: "たかい", romaji: "takai", fr: "haut / cher", img: "⬆️" },
      { jp: "低い", kana: "ひくい", romaji: "hikui", fr: "bas (peu élevé)", img: "⬇️" },
      { jp: "安い", kana: "やすい", romaji: "yasui", fr: "bon marché (adj.)", img: "🏷️" },
      { jp: "長い", kana: "ながい", romaji: "nagai", fr: "long", img: "📏" },
      { jp: "短い", kana: "みじかい", romaji: "mijikai", fr: "court", img: "✂️" },
      { jp: "広い", kana: "ひろい", romaji: "hiroi", fr: "spacieux / large", img: "🌐" },
      { jp: "狭い", kana: "せまい", romaji: "semai", fr: "étroit", img: "📦" },
      { jp: "重い", kana: "おもい", romaji: "omoi", fr: "lourd", img: "🏋️" },
      { jp: "軽い", kana: "かるい", romaji: "karui", fr: "léger", img: "🎈" },
      { jp: "強い", kana: "つよい", romaji: "tsuyoi", fr: "fort", img: "💪" },
      { jp: "弱い", kana: "よわい", romaji: "yowai", fr: "faible", img: "🥀" },
      { jp: "速い", kana: "はやい", romaji: "hayai", fr: "rapide", img: "⚡" },
      { jp: "遅い", kana: "おそい", romaji: "osoi", fr: "lent", img: "🐢" },
      { jp: "暑い", kana: "あつい", romaji: "atsui", fr: "chaud (temps)", img: "🥵" },
      { jp: "寒い", kana: "さむい", romaji: "samui", fr: "froid (temps)", img: "🥶" },
      { jp: "暖かい", kana: "あたたかい", romaji: "atatakai", fr: "doux (chaud agréable)", img: "🌤️" },
      { jp: "涼しい", kana: "すずしい", romaji: "suzushii", fr: "frais (agréable)", img: "🍃" },
      { jp: "熱い", kana: "あつい", romaji: "atsui", fr: "chaud (au toucher)", img: "🔥" },
      { jp: "冷たい", kana: "つめたい", romaji: "tsumetai", fr: "froid (au toucher)", img: "🧊" },
      { jp: "明るい", kana: "あかるい", romaji: "akarui", fr: "lumineux / gai", img: "💡" },
      { jp: "暗い", kana: "くらい", romaji: "kurai", fr: "sombre", img: "🌑" },
      { jp: "うるさい", kana: "うるさい", romaji: "urusai", fr: "bruyant", img: "🔊" },
      { jp: "静か", kana: "しずか", romaji: "shizuka", fr: "calme", img: "🤫" },
      { jp: "きれい", kana: "きれい", romaji: "kirei", fr: "joli / propre", img: "✨" },
      { jp: "汚い", kana: "きたない", romaji: "kitanai", fr: "sale", img: "🧹" },
      { jp: "美味しい", kana: "おいしい", romaji: "oishii", fr: "délicieux (adj.)", img: "😋" },
      { jp: "楽しい", kana: "たのしい", romaji: "tanoshii", fr: "amusant", img: "😄" },
      { jp: "面白い", kana: "おもしろい", romaji: "omoshiroi", fr: "intéressant / drôle", img: "😆" },
      { jp: "つまらない", kana: "つまらない", romaji: "tsumaranai", fr: "ennuyeux", img: "😐" },
      { jp: "難しい", kana: "むずかしい", romaji: "muzukashii", fr: "difficile", img: "😓" },
      { jp: "易しい", kana: "やさしい", romaji: "yasashii", fr: "facile", img: "🙂" },
      { jp: "優しい", kana: "やさしい", romaji: "yasashii", fr: "gentil", img: "🤗" },
      { jp: "忙しい", kana: "いそがしい", romaji: "isogashii", fr: "occupé", img: "🏃" },
      { jp: "暇", kana: "ひま", romaji: "hima", fr: "libre (disponible)", img: "😌" },
      { jp: "元気", kana: "げんき", romaji: "genki", fr: "en forme", img: "💪" },
      { jp: "有名", kana: "ゆうめい", romaji: "yūmei", fr: "célèbre", img: "🌟" },
      { jp: "便利", kana: "べんり", romaji: "benri", fr: "pratique", img: "🛠️" },
      { jp: "大切", kana: "たいせつ", romaji: "taisetsu", fr: "important / précieux", img: "💖" },
      { jp: "危ない", kana: "あぶない", romaji: "abunai", fr: "dangereux", img: "⚠️" },
      { jp: "安全", kana: "あんぜん", romaji: "anzen", fr: "sûr / en sécurité", img: "🛡️" },
      { jp: "若い", kana: "わかい", romaji: "wakai", fr: "jeune", img: "🧒" },
      { jp: "丸い", kana: "まるい", romaji: "marui", fr: "rond", img: "⭕" },
      { jp: "四角い", kana: "しかくい", romaji: "shikakui", fr: "carré", img: "⬛" },
      { jp: "甘い", kana: "あまい", romaji: "amai", fr: "sucré (adj.)", img: "🍬" },
    ],
  },
  {
    theme: "Expressions utiles",
    icon: "💬",
    mots: [
      { jp: "大丈夫", kana: "だいじょうぶ", romaji: "daijōbu", fr: "ça va / d'accord", img: "👌" },
      { jp: "分かりました", kana: "わかりました", romaji: "wakarimashita", fr: "j'ai compris", img: "✅" },
      { jp: "分かりません", kana: "わかりません", romaji: "wakarimasen", fr: "je ne comprends pas", img: "❓" },
      { jp: "知りません", kana: "しりません", romaji: "shirimasen", fr: "je ne sais pas", img: "🤷" },
      { jp: "ちょっと待って", kana: "ちょっとまって", romaji: "chotto matte", fr: "attends un peu", img: "✋" },
      { jp: "もう一度", kana: "もういちど", romaji: "mō ichido", fr: "encore une fois", img: "🔁" },
      { jp: "ゆっくり", kana: "ゆっくり", romaji: "yukkuri", fr: "doucement / lentement", img: "🐢" },
      { jp: "いいですよ", kana: "いいですよ", romaji: "ii desu yo", fr: "c'est bon (d'accord)", img: "👍" },
      { jp: "いいですか", kana: "いいですか", romaji: "ii desu ka", fr: "puis-je ? / c'est bon ?", img: "❔" },
      { jp: "もちろん", kana: "もちろん", romaji: "mochiron", fr: "bien sûr", img: "✔️" },
      { jp: "たぶん", kana: "たぶん", romaji: "tabun", fr: "peut-être", img: "🤔" },
      { jp: "本当", kana: "ほんとう", romaji: "hontō", fr: "vraiment", img: "‼️" },
      { jp: "うそ", kana: "うそ", romaji: "uso", fr: "mensonge / c'est pas vrai", img: "😲" },
      { jp: "すごい", kana: "すごい", romaji: "sugoi", fr: "génial / incroyable", img: "🤩" },
      { jp: "やった", kana: "やった", romaji: "yatta", fr: "j'ai réussi !", img: "🙌" },
      { jp: "頑張って", kana: "がんばって", romaji: "ganbatte", fr: "courage / bon courage", img: "💪" },
      { jp: "お大事に", kana: "おだいじに", romaji: "odaiji ni", fr: "soigne-toi", img: "🤒" },
      { jp: "気をつけて", kana: "きをつけて", romaji: "ki o tsukete", fr: "fais attention", img: "🙂" },
      { jp: "助けて", kana: "たすけて", romaji: "tasukete", fr: "au secours", img: "🆘" },
      { jp: "危ない", kana: "あぶない", romaji: "abunai", fr: "attention ! (danger)", img: "⚠️" },
      { jp: "いくらですか", kana: "いくらですか", romaji: "ikura desu ka", fr: "combien ça coûte ?", img: "💴" },
      { jp: "これは何ですか", kana: "これはなんですか", romaji: "kore wa nan desu ka", fr: "qu'est-ce que c'est ?", img: "❓" },
      { jp: "どこですか", kana: "どこですか", romaji: "doko desu ka", fr: "où est-ce ?", img: "📍" },
      { jp: "トイレはどこですか", kana: "トイレはどこですか", romaji: "toire wa doko desu ka", fr: "où sont les toilettes ?", img: "🚻" },
      { jp: "英語が話せますか", kana: "えいごがはなせますか", romaji: "eigo ga hanasemasu ka", fr: "parlez-vous anglais ?", img: "🇬🇧" },
      { jp: "もう一度お願いします", kana: "もういちどおねがいします", romaji: "mō ichido onegai shimasu", fr: "répétez, s'il vous plaît", img: "🔁" },
      { jp: "ゆっくり話してください", kana: "ゆっくりはなしてください", romaji: "yukkuri hanashite kudasai", fr: "parlez lentement", img: "🗣️" },
      { jp: "手伝ってください", kana: "てつだってください", romaji: "tetsudatte kudasai", fr: "aidez-moi, s'il vous plaît", img: "🙏" },
      { jp: "名前は何ですか", kana: "なまえはなんですか", romaji: "namae wa nan desu ka", fr: "quel est votre nom ? (question)", img: "🪪" },
      { jp: "何時ですか", kana: "なんじですか", romaji: "nanji desu ka", fr: "quelle heure est-il ?", img: "🕐" },
      { jp: "元気", kana: "げんき", romaji: "genki?", fr: "ça va ? (informel)", img: "🙂" },
      { jp: "久しぶり", kana: "ひさしぶり", romaji: "hisashiburi", fr: "ça faisait longtemps (expr.)", img: "🕰️" },
      { jp: "おめでとう", kana: "おめでとう", romaji: "omedetō", fr: "félicitations", img: "🎉" },
      { jp: "ありがとう", kana: "ありがとう", romaji: "arigatō", fr: "merci (expr.)", img: "🙏" },
      { jp: "ごめん", kana: "ごめん", romaji: "gomen", fr: "désolé (informel)", img: "😔" },
      { jp: "大好き", kana: "だいすき", romaji: "daisuki", fr: "j'adore", img: "❤️" },
      { jp: "嫌い", kana: "きらい", romaji: "kirai", fr: "je déteste", img: "💢" },
      { jp: "欲しい", kana: "ほしい", romaji: "hoshii", fr: "je veux (ceci)", img: "🙌" },
      { jp: "疲れた", kana: "つかれた", romaji: "tsukareta", fr: "je suis fatigué(e)", img: "😩" },
      { jp: "お腹が空いた", kana: "おなかがすいた", romaji: "onaka ga suita", fr: "j'ai faim", img: "🍽️" },
      { jp: "喉が渇いた", kana: "のどがかわいた", romaji: "nodo ga kawaita", fr: "j'ai soif", img: "🥤" },
      { jp: "眠い", kana: "ねむい", romaji: "nemui", fr: "j'ai sommeil", img: "😴" },
      { jp: "楽しかった", kana: "たのしかった", romaji: "tanoshikatta", fr: "c'était amusant", img: "😄" },
      { jp: "美味しかった", kana: "おいしかった", romaji: "oishikatta", fr: "c'était bon", img: "😋" },
      { jp: "また会いましょう", kana: "またあいましょう", romaji: "mata aimashō", fr: "revoyons-nous", img: "👋" },
      { jp: "気にしないで", kana: "きにしないで", romaji: "ki ni shinaide", fr: "ne t'en fais pas (expr.)", img: "🙂" },
      { jp: "どうしたの", kana: "どうしたの", romaji: "dōshita no", fr: "qu'est-ce qu'il y a ?", img: "🤔" },
      { jp: "なるほど", kana: "なるほど", romaji: "naruhodo", fr: "je vois / en effet", img: "💡" },
      { jp: "そうですね", kana: "そうですね", romaji: "sō desu ne", fr: "c'est vrai / en effet", img: "🙂" },
      { jp: "やめて", kana: "やめて", romaji: "yamete", fr: "arrête", img: "🛑" },
    ],
  },
];

/* Exposé global (utilisé par data.js) */
if (typeof window !== "undefined") window.VOCABULAIRE = VOCABULAIRE;
